"""Canonical Python package for neuralspotx tooling."""

from .api import (
    AppActionRequest,
    AppBuildRequest,
    AppCleanRequest,
    AppCreateRequest,
    AppFlashRequest,
    ModuleChangeRequest,
    ModuleRegisterRequest,
    ModuleUpdateRequest,
    NSXError,
    add_module,
    build_app,
    clean_app,
    configure_app,
    create_app,
    describe_module,
    doctor,
    find_app_root,
    flash_app,
    list_modules,
    register_module,
    remove_module,
    resolve_app_dir,
    search_modules,
    update_modules,
    validate_module_metadata,
    view_app,
)
from .cli import main

__all__ = [
    "AppActionRequest",
    "AppBuildRequest",
    "AppCleanRequest",
    "AppCreateRequest",
    "AppFlashRequest",
    "ModuleChangeRequest",
    "ModuleRegisterRequest",
    "ModuleUpdateRequest",
    "NSXError",
    "add_module",
    "build_app",
    "clean_app",
    "configure_app",
    "create_app",
    "describe_module",
    "doctor",
    "find_app_root",
    "flash_app",
    "list_modules",
    "main",
    "register_module",
    "remove_module",
    "resolve_app_dir",
    "search_modules",
    "update_modules",
    "validate_module_metadata",
    "view_app",
]
