# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, Ambiq
"""Canonical Python package for neuralspotx tooling.

The names exposed here form the **public Python API** of NSX. Anything
importable from a private ``_<name>`` module is, by convention,
internal and may change without notice.

See ``docs/reference/public-api.md`` for the canonical list with
stability tiers. ``tests/test_public_surface_doc.py`` keeps the doc
and ``__all__`` from drifting.
"""

from ._errors import (
    NSXCacheError,
    NSXConfigError,
    NSXError,
    NSXGitError,
    NSXIntegrityError,
    NSXLockError,
    NSXModuleError,
    NSXResolutionError,
    NSXTimeoutError,
    NSXToolchainError,
)
from ._io import Emitter, Event, default_emitter
from .api import (
    AppActionRequest,
    AppBuildRequest,
    AppCleanRequest,
    AppCreateRequest,
    AppFlashRequest,
    AppLockRequest,
    AppOutdatedRequest,
    AppSyncRequest,
    AppUpdateRequest,
    AppViewRequest,
    BoardCreateRequest,
    ModuleChangeRequest,
    ModuleInitRequest,
    ModuleRegisterRequest,
    ModuleUpdateRequest,
    add_module,
    build_app,
    cache_info,
    clean_app,
    clean_cache,
    configure_app,
    create_app,
    create_board,
    describe_module,
    doctor,
    find_app_root,
    flash_app,
    generate_sbom,
    init_module,
    list_modules,
    load_registry,
    lock_app,
    outdated_app,
    register_module,
    registry_module_project,
    remove_module,
    reset_target,
    resolve_app_dir,
    search_modules,
    starter_profile,
    sync_app,
    update_app,
    update_modules,
    validate_module_metadata,
    view_app,
)
from .models import (
    CacheCleanResult,
    CacheEntry,
    CacheInfo,
    CommandCategory,
    CommandHint,
    CommandScope,
    DiscoveryRecord,
    DoctorCheck,
    DoctorReport,
    FlashResult,
    ModuleChange,
    OutdatedModule,
    OutdatedReport,
    OutdatedSkip,
    ResetResult,
    SearchMatch,
    SearchResult,
)
from .nsx_lock import LockKind, NsxLock, ResolvedModule
from .operations import OutdatedStatus, ProfileStatus

__all__ = [
    # Request dataclasses
    "AppActionRequest",
    "AppBuildRequest",
    "AppCleanRequest",
    "AppCreateRequest",
    "AppFlashRequest",
    "AppLockRequest",
    "AppOutdatedRequest",
    "AppSyncRequest",
    "AppUpdateRequest",
    "AppViewRequest",
    "BoardCreateRequest",
    "ModuleChangeRequest",
    "ModuleInitRequest",
    "ModuleRegisterRequest",
    "ModuleUpdateRequest",
    # Result / data models
    "CacheCleanResult",
    "CacheEntry",
    "CacheInfo",
    "CommandCategory",
    "CommandHint",
    "CommandScope",
    "DiscoveryRecord",
    "DoctorCheck",
    "DoctorReport",
    "FlashResult",
    "ModuleChange",
    "OutdatedModule",
    "OutdatedReport",
    "OutdatedSkip",
    "ResetResult",
    "SearchMatch",
    "SearchResult",
    # Lock model + enums
    "LockKind",
    "NsxLock",
    "OutdatedStatus",
    "ProfileStatus",
    "ResolvedModule",
    # Errors
    "NSXCacheError",
    "NSXConfigError",
    "NSXError",
    "NSXGitError",
    "NSXIntegrityError",
    "NSXLockError",
    "NSXModuleError",
    "NSXResolutionError",
    "NSXTimeoutError",
    "NSXToolchainError",
    # Structured emitter
    "Emitter",
    "Event",
    "default_emitter",
    # API callables
    "add_module",
    "build_app",
    "cache_info",
    "clean_app",
    "clean_cache",
    "configure_app",
    "create_app",
    "create_board",
    "describe_module",
    "doctor",
    "find_app_root",
    "flash_app",
    "reset_target",
    "generate_sbom",
    "init_module",
    "list_modules",
    "lock_app",
    "load_registry",
    "outdated_app",
    "registry_module_project",
    "register_module",
    "remove_module",
    "resolve_app_dir",
    "search_modules",
    "starter_profile",
    "sync_app",
    "update_app",
    "update_modules",
    "validate_module_metadata",
    "view_app",
]
