"""Helpers for app config, workspace layout, and packaged registry assets."""

from __future__ import annotations

import argparse
import copy
import importlib.resources as resources
from pathlib import Path
from typing import Any

import yaml

from .metadata import load_registry_lock
from .subprocess_utils import run


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _load_registry() -> dict[str, Any]:
    registry_resource = resources.files("neuralspotx.data").joinpath("registry.lock.yaml")
    with resources.as_file(registry_resource) as registry_path:
        return load_registry_lock(registry_path)


def _effective_registry(base_registry: dict[str, Any], nsx_cfg: dict[str, Any]) -> dict[str, Any]:
    merged = copy.deepcopy(base_registry)
    overrides = nsx_cfg.get("module_registry", {})
    if not isinstance(overrides, dict):
        return merged

    projects = overrides.get("projects", {})
    modules = overrides.get("modules", {})
    if not isinstance(projects, dict) or not isinstance(modules, dict):
        return merged

    merged.setdefault("projects", {})
    merged.setdefault("modules", {})
    for name, override in projects.items():
        if not isinstance(name, str) or not isinstance(override, dict):
            continue
        current = merged["projects"].get(name, {})
        if not isinstance(current, dict):
            current = {}
        current.update(override)
        merged["projects"][name] = current
    for name, override in modules.items():
        if not isinstance(name, str) or not isinstance(override, dict):
            continue
        current = merged["modules"].get(name, {})
        if not isinstance(current, dict):
            current = {}
        current.update(override)
        merged["modules"][name] = current
    return merged


def _registry_project_entry(registry: dict[str, Any], project_name: str) -> dict[str, Any]:
    projects = registry.get("projects", {})
    if not isinstance(projects, dict):
        return {}
    entry = projects.get(project_name, {})
    return entry if isinstance(entry, dict) else {}


def _render_west_manifest(
    nsx_repo_url: str,
    nsx_revision: str,
    ambiqsuite_url: str | None,
    ambiqsuite_revision: str,
    *,
    manifest_template: str,
    repo_name: str,
) -> str:
    ambiq_block = ""
    if ambiqsuite_url:
        ambiq_block = (
            "    - name: \"ambiqsuite\"\n"
            f"      url: \"{ambiqsuite_url}\"\n"
            f"      revision: \"{ambiqsuite_revision}\"\n"
            "      path: \"modules/ambiqsuite\"\n"
        )
    return (
        manifest_template.replace("__NSX_REPO_NAME__", repo_name)
        .replace("__NSX_REPO_URL__", nsx_repo_url)
        .replace("__NSX_REVISION__", nsx_revision)
        .replace("__AMBIQ_PROJECT_BLOCK__", ambiq_block)
    )


def _read_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _write_yaml(path: Path, data: dict[str, Any]) -> None:
    path.write_text(
        yaml.safe_dump(data, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )


def _copy_packaged_tree(package: str, relative_path: str, destination: Path) -> None:
    source_resource = resources.files(package).joinpath(relative_path)
    with resources.as_file(source_resource) as src:
        if destination.exists():
            import shutil

            shutil.rmtree(destination)
        import shutil

        shutil.copytree(
            src,
            destination,
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns("__pycache__"),
        )


def _write_app_module_file(
    app_dir: Path,
    nsx_cfg: dict[str, Any],
) -> None:
    modules = nsx_cfg.get("modules", [])
    lines = [
        "# Auto-generated by neuralspotx. Included by app CMakeLists.",
        "set(NSX_APP_MODULES",
    ]
    for item in modules:
        if isinstance(item, dict) and isinstance(item.get("name"), str):
            lines.append(f"    {item['name']}")
    lines.append(")")
    content = "\n".join(lines) + "\n"
    (app_dir / "cmake" / "nsx").mkdir(parents=True, exist_ok=True)
    (app_dir / "cmake" / "nsx" / "modules.cmake").write_text(content, encoding="utf-8")


def _vendored_metadata_relpath(metadata: str) -> Path:
    path = Path(metadata)
    parts = path.parts
    if "boards" in parts:
        idx = parts.index("boards")
        return Path(*parts[idx:])
    if "cmake" in parts:
        idx = parts.index("cmake")
        return Path(*parts[idx:])
    if len(parts) >= 2:
        return Path("modules") / parts[0] / Path(*parts[1:])
    return Path("modules") / path


def _vendored_target_dir(app_dir: Path, module_name: str, metadata: str) -> Path:
    rel = _vendored_metadata_relpath(metadata)
    if rel.parts[:1] == ("boards",) and len(rel.parts) >= 2:
        return app_dir / "boards" / rel.parts[1]
    if rel.parts[:1] == ("cmake",):
        return app_dir / "cmake" / "nsx"
    if rel.parts[:1] == ("modules",) and len(rel.parts) >= 2:
        if rel.parts[1].endswith(".yaml") or rel.parts[1].endswith(".yml"):
            return app_dir / "modules" / module_name
        return app_dir / "modules" / rel.parts[1]
    return app_dir / "modules" / module_name


def _metadata_path_relative_to_project(metadata: Path, project_path: str | None) -> Path:
    if not metadata.is_absolute():
        if project_path is not None:
            project_parts = Path(project_path).parts
            if metadata.parts[: len(project_parts)] == project_parts:
                return Path(*metadata.parts[len(project_parts) :])
        return metadata
    return metadata.name


def _project_checkout_candidates(
    project_name: str,
    registry: dict[str, Any],
    workspace: Path,
) -> list[Path]:
    project_entry = _registry_project_entry(registry, project_name)
    project_path = project_entry.get("path")
    candidates: list[Path] = []

    local_path = project_entry.get("local_path")
    if isinstance(local_path, str):
        candidates.append(Path(local_path).expanduser())

    if isinstance(project_path, str):
        candidates.append(workspace / project_path)

    unique: list[Path] = []
    for candidate in candidates:
        resolved = candidate.resolve()
        if resolved not in unique:
            unique.append(resolved)
    return unique


def _require_initialized_workspace(workspace: Path) -> None:
    if (workspace / ".west").exists() and (workspace / "manifest" / "west.yml").exists():
        return
    raise SystemExit(
        f"Workspace is not initialized: {workspace}\n"
        "Run `nsx init-workspace <workspace>` before creating apps or syncing modules."
    )


def _workspace_for_app_dir(app_dir: Path) -> Path:
    nsx_cfg = app_dir / "nsx.yml"
    if nsx_cfg.exists():
        cfg = _read_yaml(nsx_cfg)
        west_manifest = cfg.get("west", {}).get("manifest")
        if isinstance(west_manifest, str):
            manifest_path = (app_dir / west_manifest).resolve()
            if manifest_path.exists():
                return manifest_path.parent.parent

    for parent in [app_dir, *app_dir.parents]:
        if (parent / ".west").exists():
            return parent
        if (parent / "manifest" / "west.yml").exists():
            return parent
    if (app_dir / "cmake" / "nsx").exists():
        return app_dir
    raise SystemExit(f"Unable to determine workspace root from app dir: {app_dir}")


def _metadata_storage_path(app_dir: Path, metadata_path: Path, project_entry: dict[str, Any]) -> str:
    local_path = project_entry.get("local_path")
    if isinstance(local_path, str):
        local_root = Path(local_path).expanduser().resolve()
        try:
            return str(metadata_path.resolve().relative_to(local_root))
        except ValueError:
            pass

    project_path = project_entry.get("path")
    if isinstance(project_path, str):
        project_root = (_workspace_for_app_dir(app_dir) / project_path).resolve()
        try:
            metadata_rel = metadata_path.resolve().relative_to(project_root)
            return str(Path(project_path) / metadata_rel)
        except ValueError:
            pass

    try:
        return str(metadata_path.resolve().relative_to(app_dir.resolve()))
    except ValueError:
        return str(metadata_path.resolve())


def _packaged_metadata_path(metadata: Path) -> Path | None:
    parts = metadata.parts
    if len(parts) >= 4 and tuple(parts[:2]) == ("src", "neuralspotx") and parts[2] == "boards":
        resource = resources.files("neuralspotx").joinpath("boards", *parts[3:])
    elif len(parts) >= 3 and tuple(parts[:3]) == ("src", "neuralspotx", "cmake"):
        resource = resources.files("neuralspotx").joinpath("cmake", *parts[3:])
    else:
        return None

    with resources.as_file(resource) as resource_path:
        if resource_path.exists():
            return resource_path
    return None


def _unique_preserving_order(module_names: list[str]) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []
    for name in module_names:
        if name in seen:
            continue
        seen.add(name)
        ordered.append(name)
    return ordered


def _app_name_from_cfg(nsx_cfg: dict[str, Any]) -> str:
    project = nsx_cfg.get("project", {})
    name = project.get("name")
    if not isinstance(name, str) or not name:
        raise SystemExit("nsx.yml missing project.name")
    return name


def _default_build_dir(app_dir: Path, board: str) -> Path:
    return app_dir / "build" / board


def _run_cmake_configure(app_dir: Path, build_dir: Path, board: str) -> None:
    toolchain_file = app_dir / "cmake" / "nsx" / "toolchains" / "arm-none-eabi-gcc.cmake"
    run(
        [
            "cmake",
            "-S",
            str(app_dir),
            "-B",
            str(build_dir),
            "-G",
            "Ninja",
            f"-DCMAKE_TOOLCHAIN_FILE={toolchain_file}",
            "-DCMAKE_BUILD_TYPE=Release",
            f"-DNSX_BOARD={board}",
        ]
    )


def _resolve_app_context(args: argparse.Namespace) -> tuple[Path, Path, dict[str, Any], str, str]:
    app_dir = Path(args.app_dir).expanduser().resolve()
    nsx_cfg = _load_app_cfg(app_dir)
    app_name = _app_name_from_cfg(nsx_cfg)
    board = args.board or nsx_cfg.get("target", {}).get("board")
    if not isinstance(board, str) or not board:
        raise SystemExit("Unable to determine target board from args or nsx.yml")
    workspace = _workspace_for_app_dir(app_dir)
    return app_dir, workspace, nsx_cfg, app_name, board


def _load_app_cfg(app_dir: Path) -> dict[str, Any]:
    cfg_path = app_dir / "nsx.yml"
    if not cfg_path.exists():
        raise SystemExit(f"App config not found: {cfg_path}")
    cfg = _read_yaml(cfg_path)
    if cfg.get("schema_version") != 1:
        raise SystemExit(f"{cfg_path}: unsupported schema_version={cfg.get('schema_version')}")
    return cfg


def _save_app_cfg(app_dir: Path, cfg: dict[str, Any]) -> None:
    _write_yaml(app_dir / "nsx.yml", cfg)


def _manifest_projects_by_name(workspace: Path) -> dict[str, dict[str, Any]]:
    manifest_path = workspace / "manifest" / "west.yml"
    data = _read_yaml(manifest_path)
    manifest = data.get("manifest", {})
    projects = manifest.get("projects", [])
    if not isinstance(projects, list):
        return {}
    out: dict[str, dict[str, Any]] = {}
    for proj in projects:
        if not isinstance(proj, dict):
            continue
        name = proj.get("name")
        if isinstance(name, str):
            out[name] = proj
    return out


def _workspace_has_manifest(workspace: Path) -> bool:
    return (workspace / "manifest" / "west.yml").exists()
