"""Helpers for app config, registry assets, and build integration."""

from __future__ import annotations

import argparse
import copy
import importlib.resources as resources
import os
from pathlib import Path
from typing import Any

from importlib.metadata import PackageNotFoundError, version as package_version

import yaml

from .constants import PACKAGED_PROJECT_NAME
from .metadata import load_registry_lock
from .models import ProjectEntry
from .subprocess_utils import run


def _load_registry() -> dict[str, Any]:
    registry_resource = resources.files("neuralspotx.data").joinpath("registry.lock.yaml")
    with resources.as_file(registry_resource) as registry_path:
        return load_registry_lock(registry_path)


def _effective_registry(base_registry: dict[str, Any], nsx_cfg: dict[str, Any]) -> dict[str, Any]:
    merged = copy.deepcopy(base_registry)
    overrides = nsx_cfg.get("module_registry", {})
    if not isinstance(overrides, dict):
        return merged

    projects = overrides.get("projects", {})
    modules = overrides.get("modules", {})
    if not isinstance(projects, dict) or not isinstance(modules, dict):
        return merged

    merged.setdefault("projects", {})
    merged.setdefault("modules", {})
    for name, override in projects.items():
        if not isinstance(name, str) or not isinstance(override, dict):
            continue
        current = merged["projects"].get(name, {})
        if not isinstance(current, dict):
            current = {}
        current.update(override)
        merged["projects"][name] = current
    for name, override in modules.items():
        if not isinstance(name, str) or not isinstance(override, dict):
            continue
        current = merged["modules"].get(name, {})
        if not isinstance(current, dict):
            current = {}
        current.update(override)
        merged["modules"][name] = current
    return merged


def _registry_project_entry(registry: dict[str, Any], project_name: str) -> ProjectEntry:
    projects = registry.get("projects", {})
    if not isinstance(projects, dict):
        return ProjectEntry(name=project_name)
    return ProjectEntry.from_mapping(project_name, projects.get(project_name))


def _nsx_tool_version() -> str | None:
    try:
        return package_version("neuralspotx")
    except PackageNotFoundError:
        return None


def _nsx_tool_major(version_text: str | None) -> int | None:
    if not version_text:
        return None
    head = version_text.split(".", 1)[0]
    return int(head) if head.isdigit() else None



def _check_nsx_version_compatibility(cfg: dict[str, Any], cfg_path: Path) -> None:
    tooling = cfg.get("tooling", {})
    if not isinstance(tooling, dict):
        return
    nsx_info = tooling.get("nsx", {})
    if not isinstance(nsx_info, dict):
        return

    recorded_major = nsx_info.get("major")
    if not isinstance(recorded_major, int):
        return

    current_version = _nsx_tool_version()
    current_major = _nsx_tool_major(current_version)
    if current_major is None or recorded_major == current_major:
        return

    if os.getenv("NSX_ALLOW_VERSION_MISMATCH"):
        return

    recorded_version = nsx_info.get("version")
    raise SystemExit(
        f"{cfg_path}: app was created with nsx {recorded_version or recorded_major}, "
        f"but current nsx major version is {current_major}. "
        "Set NSX_ALLOW_VERSION_MISMATCH=1 to bypass this check for now."
    )


def _read_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _write_yaml(path: Path, data: dict[str, Any]) -> None:
    path.write_text(
        yaml.safe_dump(data, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )


def _copy_packaged_tree(package: str, relative_path: str, destination: Path) -> None:
    source_resource = resources.files(package).joinpath(relative_path)
    with resources.as_file(source_resource) as src:
        if destination.exists():
            import shutil

            shutil.rmtree(destination)
        import shutil

        shutil.copytree(
            src,
            destination,
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns("__pycache__"),
        )


def _write_app_module_file(
    app_dir: Path,
    nsx_cfg: dict[str, Any],
) -> None:
    modules = nsx_cfg.get("modules", [])
    lines = [
        "# Auto-generated by neuralspotx. Included by app CMakeLists.",
        "set(NSX_APP_MODULES",
    ]
    for item in modules:
        if isinstance(item, dict) and isinstance(item.get("name"), str):
            lines.append(f"    {item['name']}")
    lines.append(")")
    content = "\n".join(lines) + "\n"
    (app_dir / "cmake" / "nsx").mkdir(parents=True, exist_ok=True)
    (app_dir / "cmake" / "nsx" / "modules.cmake").write_text(content, encoding="utf-8")


def _write_modules_gitignore(app_dir: Path, nsx_cfg: dict[str, Any]) -> None:
    """Generate ``modules/.gitignore`` to ignore registry modules but keep local ones.

    Registry modules are re-acquired automatically by ``nsx configure``.
    Modules marked ``local: true`` in nsx.yml are source-controlled and
    must NOT be ignored.
    """

    modules = nsx_cfg.get("modules", [])
    local_names: set[str] = set()
    registry_names: list[str] = []
    for item in modules:
        if not isinstance(item, dict):
            continue
        name = item.get("name")
        if not isinstance(name, str):
            continue
        if item.get("local"):
            local_names.add(name)
        else:
            registry_names.append(name)

    lines = [
        "# Auto-generated by neuralspotx — do not edit.",
        "# Registry modules are re-acquired by `nsx configure`.",
    ]
    for name in sorted(registry_names):
        lines.append(f"{name}/")
    if local_names:
        lines.append("")
        lines.append("# Local modules (source-controlled) are NOT ignored:")
        for name in sorted(local_names):
            lines.append(f"# {name}/")
    lines.append("")
    (app_dir / "modules").mkdir(parents=True, exist_ok=True)
    (app_dir / "modules" / ".gitignore").write_text("\n".join(lines), encoding="utf-8")


def _vendored_metadata_relpath(metadata: str) -> Path:
    path = Path(metadata)
    parts = path.parts
    if parts[:1] == ("modules",):
        return path
    if "boards" in parts:
        idx = parts.index("boards")
        return Path(*parts[idx:])
    if "cmake" in parts:
        idx = parts.index("cmake")
        return Path(*parts[idx:])
    if len(parts) >= 2:
        return Path("modules") / parts[0] / Path(*parts[1:])
    return Path("modules") / path


def _vendored_target_dir(app_dir: Path, module_name: str, metadata: str) -> Path:
    rel = _vendored_metadata_relpath(metadata)
    if rel.parts[:1] == ("boards",) and len(rel.parts) >= 2:
        return app_dir / "boards" / rel.parts[1]
    if rel.parts[:1] == ("cmake",):
        return app_dir / "cmake" / "nsx"
    if rel.parts[:1] == ("modules",) and len(rel.parts) >= 2:
        if rel.parts[1].endswith(".yaml") or rel.parts[1].endswith(".yml"):
            return app_dir / "modules" / module_name
        return app_dir / "modules" / rel.parts[1]
    return app_dir / "modules" / module_name


def _metadata_path_relative_to_project(metadata: Path, project_path: str | None) -> Path:
    if not metadata.is_absolute():
        if project_path is not None:
            project_parts = Path(project_path).parts
            if metadata.parts[: len(project_parts)] == project_parts:
                return Path(*metadata.parts[len(project_parts) :])
        return metadata
    return metadata.name


def _is_packaged_module(registry: dict[str, Any], module_name: str) -> bool:
    """Return True if *module_name* ships packaged with neuralspotx."""

    from .metadata import registry_entry_for_module

    entry = registry_entry_for_module(registry, module_name)
    return entry.project == PACKAGED_PROJECT_NAME


def _module_clone_dir(app_dir: Path, project_name: str, registry: dict | None = None) -> Path:
    """Return the local clone destination for a module project.

    Uses the project's ``path`` field from the registry when available,
    otherwise falls back to ``modules/<project_name>``.
    """

    if registry is not None:
        project_entry = registry.get("projects", {}).get(project_name, {})
        project_path = project_entry.get("path") if isinstance(project_entry, dict) else None
        if project_path:
            return app_dir / project_path

    return app_dir / "modules" / project_name


def find_app_root(start: Path | None = None) -> Path | None:
    """Walk upward from *start* to find the nearest ``nsx.yml``.

    Stops at the filesystem root or a git repository boundary (a directory
    containing ``.git``).  Returns the resolved directory containing
    ``nsx.yml``, or ``None`` when no app root is found.
    """

    current = (start or Path.cwd()).expanduser().resolve()
    while True:
        if (current / "nsx.yml").exists():
            return current
        # Stop at git boundary — do not cross into a parent repo.
        if (current / ".git").exists():
            return None
        parent = current.parent
        if parent == current:
            return None
        current = parent


def resolve_app_dir(explicit: str | Path | None) -> Path:
    """Return a resolved app directory from an explicit path or upward walk.

    When *explicit* is given (and is not ``"."``), it is returned directly.
    Otherwise, :func:`find_app_root` searches from the current directory.
    """

    if explicit is not None and str(explicit) != ".":
        return Path(explicit).expanduser().resolve()

    found = find_app_root()
    if found is not None:
        return found
    # Fall back to explicit value (usually ".") so downstream code
    # produces a clear "nsx.yml not found" error.
    return Path(explicit or ".").expanduser().resolve()


def _require_app_config(app_dir: Path) -> None:
    """Fail if *app_dir* does not contain an ``nsx.yml``."""

    if (app_dir / "nsx.yml").exists():
        return
    raise SystemExit(
        f"NSX app config not found: {app_dir / 'nsx.yml'}\n"
        "Run `nsx create-app <app-dir>` to create a new app."
    )


def _metadata_storage_path(app_dir: Path, metadata_path: Path, project_entry: ProjectEntry) -> str:
    if project_entry.local_path:
        local_root = Path(project_entry.local_path).expanduser().resolve()
        try:
            return str(metadata_path.resolve().relative_to(local_root))
        except ValueError:
            pass

    if project_entry.path:
        clone_dir = app_dir / project_entry.path
        try:
            metadata_rel = metadata_path.resolve().relative_to(clone_dir.resolve())
            return str(Path(project_entry.path) / metadata_rel)
        except ValueError:
            pass

    try:
        return str(metadata_path.resolve().relative_to(app_dir.resolve()))
    except ValueError:
        return str(metadata_path.resolve())


def _packaged_metadata_path(metadata: Path) -> Path | None:
    parts = metadata.parts
    if len(parts) >= 4 and tuple(parts[:2]) == ("src", "neuralspotx") and parts[2] == "boards":
        resource = resources.files("neuralspotx").joinpath("boards", *parts[3:])
    elif len(parts) >= 3 and tuple(parts[:3]) == ("src", "neuralspotx", "cmake"):
        resource = resources.files("neuralspotx").joinpath("cmake", *parts[3:])
    else:
        return None

    with resources.as_file(resource) as resource_path:
        if resource_path.exists():
            return resource_path
    return None


def _unique_preserving_order(module_names: list[str]) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []
    for name in module_names:
        if name in seen:
            continue
        seen.add(name)
        ordered.append(name)
    return ordered


def _app_name_from_cfg(nsx_cfg: dict[str, Any]) -> str:
    project = nsx_cfg.get("project", {})
    name = project.get("name")
    if not isinstance(name, str) or not name:
        raise SystemExit("nsx.yml missing project.name")
    return name


def _default_build_dir(app_dir: Path, board: str) -> Path:
    return app_dir / "build" / board


def _run_cmake_configure(app_dir: Path, build_dir: Path, board: str) -> None:
    toolchain_file = app_dir / "cmake" / "nsx" / "toolchains" / "arm-none-eabi-gcc.cmake"
    run(
        [
            "cmake",
            "-S",
            str(app_dir),
            "-B",
            str(build_dir),
            "-G",
            "Ninja",
            f"-DCMAKE_TOOLCHAIN_FILE={toolchain_file}",
            "-DCMAKE_BUILD_TYPE=Release",
            f"-DNSX_BOARD={board}",
        ]
    )


def _resolve_app_context(args: argparse.Namespace) -> tuple[Path, dict[str, Any], str, str]:
    app_dir = Path(args.app_dir).expanduser().resolve()
    nsx_cfg = _load_app_cfg(app_dir)
    app_name = _app_name_from_cfg(nsx_cfg)
    board = args.board or nsx_cfg.get("target", {}).get("board")
    if not isinstance(board, str) or not board:
        raise SystemExit("Unable to determine target board from args or nsx.yml")
    return app_dir, nsx_cfg, app_name, board


def _load_app_cfg(app_dir: Path) -> dict[str, Any]:
    cfg_path = app_dir / "nsx.yml"
    if not cfg_path.exists():
        raise SystemExit(f"App config not found: {cfg_path}")
    cfg = _read_yaml(cfg_path)
    if cfg.get("schema_version") != 1:
        raise SystemExit(f"{cfg_path}: unsupported schema_version={cfg.get('schema_version')}")
    _check_nsx_version_compatibility(cfg, cfg_path)
    return cfg


def _save_app_cfg(app_dir: Path, cfg: dict[str, Any]) -> None:
    _write_yaml(app_dir / "nsx.yml", cfg)
