/******************************************************************************
 * @file        resnet_reshape_13.c
 * @brief       Autogenerated AOT reshape kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '13' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_reshape_13.h"


int32_t
resnet_reshape_13_init(
    resnet_model_context_t *ctx
) {
    return 0;
}

int32_t
resnet_reshape_13_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {
    if (input == output) { return 0; }

    arm_memcpy_s8(
        (int8_t *)output,
        (int8_t *)input,
        112
    );

    return 0;

}