/******************************************************************************
 * @file        resnet_conv_2d_10.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '10' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_conv_2d_10.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_10_input_dims = {
    .n = 1, .h = 16,
    .w = 16, .c = 56
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_10_filter_dims = {
    .n =  112, .h = 1,
    .w = 1, .c = 56
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_10_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 112
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_10_output_dims = {
    .n = 1, .h = 8,
    .w = 8, .c = 112
};


// Quantization parameters (per-channel quantization)
static const int32_t conv_2d_10_multiplier[112] = {
    1112763439, 1256317945, 1562849704, 1215974944, 1544262727, 1621024642, 1192470482, 1083973596,
    2115591310, 1918491595, 1465445764, 1488390525, 1733214036, 1935795062, 1358059636, 1469972667,
    1303729826, 1179248240, 1645003557, 1225520096, 2140188459, 1187745685, 1250986700, 1757444076,
    1801036461, 1125476657, 1435001177, 2070282602, 1497159129, 1665828647, 1709668719, 1190935456,
    1905760404, 1401177273, 1593406349, 1472180237, 2091954853, 1335367667, 2142095702, 1113901204,
    1350054322, 1776515720, 1956846232, 1680922580, 1505984596, 1500504563, 2062440121, 1654318013,
    1175464690, 1213612594, 2088875766, 1110634928, 2123025825, 1735037015, 1359169510, 1850092676,
    1992765451, 2087505733, 1904666342, 1170185890, 2022691291, 1133526362, 1547613661, 1272592267,
    2071873608, 1235934998, 1548590853, 1772250645, 1622486894, 1169333130, 1965818720, 1179679088,
    1192103667, 1292834283, 1615660103, 1328536752, 1923569850, 1543321775, 1768647704, 1243807237,
    1674091664, 1446370584, 1789846386, 1933821429, 1777781453, 1568285641, 1373547981, 1295438426,
    1410676561, 1706375730, 1705715757, 2049694002, 1940950117, 2103254335, 2145914313, 1740888578,
    1380795504, 1090834662, 1143566591, 1140647194, 1547510835, 1989534137, 1927304197, 2044566052,
    1141801360, 1923037354, 1874003532, 1596217814, 2080742582, 1288676355, 1912255637, 1424778570
};

static const int32_t conv_2d_10_shift[112] = {
    -10, -9, -10, -9, -10, -11, -10, -10,
    -10, -10, -10, -11, -11, -11, -10, -10,
    -10, -9, -10, -10, -11, -10, -9, -11,
    -10, -9, -10, -11, -10, -10, -10, -10,
    -10, -10, -11, -9, -10, -10, -11, -9,
    -10, -10, -10, -10, -10, -10, -11, -11,
    -10, -10, -10, -10, -10, -11, -10, -10,
    -11, -10, -10, -10, -11, -10, -11, -10,
    -11, -9, -10, -11, -10, -10, -11, -10,
    -10, -10, -10, -10, -10, -10, -10, -10,
    -11, -10, -10, -10, -10, -10, -10, -10,
    -10, -10, -11, -11, -10, -10, -10, -10,
    -10, -9, -9, -10, -10, -11, -10, -11,
    -10, -11, -10, -10, -10, -10, -10, -10
};

static const int32_t conv_2d_10_input_zero_point = -128;
static const int32_t conv_2d_10_output_zero_point = -58;


// Scratch buffer context
static cmsis_nn_context conv_2d_10_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context conv_2d_10_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_per_channel_quant_params conv_2d_10_quant_params = {
    .multiplier = (int32_t*)conv_2d_10_multiplier,
    .shift = (int32_t*)conv_2d_10_shift,
};

const cmsis_nn_conv_params conv_2d_10_params = {
    .input_offset = -conv_2d_10_input_zero_point,
    .output_offset = conv_2d_10_output_zero_point,
    .stride.w = 2,
    .stride.h = 2,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
resnet_conv_2d_10_init(
    resnet_model_context_t *ctx
) {

    conv_2d_10_ctx.buf = NULL;
    conv_2d_10_ctx.size = 0;

    conv_2d_10_weight_sum_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_10_weight_sum];
    conv_2d_10_weight_sum_ctx.size = 448;

    return ARM_CMSIS_NN_SUCCESS;

}

int32_t
resnet_conv_2d_10_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    // Bias pointer
    const int32_t *conv_2d_10_bias_ptr = NULL;

    return arm_convolve_1x1_s8(
        &conv_2d_10_ctx,
        &conv_2d_10_weight_sum_ctx,
        &conv_2d_10_params,
        &conv_2d_10_quant_params,
        &conv_2d_10_input_dims,
        input,
        &conv_2d_10_filter_dims,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_5],
        &conv_2d_10_bias_dims,
        conv_2d_10_bias_ptr,
        &conv_2d_10_output_dims,
        output
    );

}