/******************************************************************************
 * @file        resnet_fully_connected_14.c
 * @brief       Autogenerated AOT fully_connected kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '14' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/


#include "resnet_common.h"
#include "resnet_fully_connected_14.h"

// Input dimensions:
//   .n = flattened batch size (product of all input dims except the last),
//   .c = input feature size (last dimension of the input tensor).
static const cmsis_nn_dims fully_connected_14_input_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 112
};

// Filter dimensions:
//   .n = number of output channels (C_OUT),
//   .c = input feature size matching the input tensor's last dimension.
static const cmsis_nn_dims fully_connected_14_filter_dims = {
    .n = 112, .h = 1,
    .w = 1, .c = 10
};

// Bias dimensions:
//   one bias per output channel (.c = C_OUT), broadcast over the flattened batch.
static const cmsis_nn_dims fully_connected_14_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 10
};

// Output dimensions:
//   .n = flattened batch size (matches input .n),
//   .c = output feature size (C_OUT).
static const cmsis_nn_dims fully_connected_14_output_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 10
};

// Quantization parameters
static const int32_t fully_connected_14_multiplier[1] = {
    1591808198
};
static const int32_t fully_connected_14_shift[1] = {
    -6
};

static const int32_t fully_connected_14_input_zero_point = -128;
static const int32_t fully_connected_14_filter_zero_point = 0;
static const int32_t fully_connected_14_output_zero_point = 21;

// Scratch buffer context
static cmsis_nn_context fully_connected_14_ctx = {
    .buf = NULL,
    .size = 0
};

static cmsis_nn_fc_params fully_connected_14_params = {
    .input_offset = -fully_connected_14_input_zero_point,
    .filter_offset = -fully_connected_14_filter_zero_point,
    .output_offset = fully_connected_14_output_zero_point,
    .activation.min = -128,
    .activation.max = 127,
};

const cmsis_nn_per_tensor_quant_params fully_connected_14_quant_params = {
    .multiplier = fully_connected_14_multiplier[0],
    .shift = fully_connected_14_shift[0],
};


int32_t
resnet_fully_connected_14_init(
    resnet_model_context_t *ctx
) {
    fully_connected_14_ctx.buf = ctx->tensor_ptrs[resnet_tensor_fully_connected_14_weight_sum];
    fully_connected_14_ctx.size = 40;

    // Kernel sums precomputed offline.
    return ARM_CMSIS_NN_SUCCESS;
}

int32_t
resnet_fully_connected_14_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    return arm_fully_connected_s8(
        &fully_connected_14_ctx,
        &fully_connected_14_params,
        &fully_connected_14_quant_params,
        &fully_connected_14_input_dims,
        input,
        &fully_connected_14_filter_dims,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_3],
        &fully_connected_14_bias_dims,
        NULL,
        &fully_connected_14_output_dims,
        output
    );

}