/******************************************************************************
 * @file        resnet_conv_2d_0.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '0' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_conv_2d_0.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_0_input_dims = {
    .n = 1, .h = 32,
    .w = 32, .c = 3
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_0_filter_dims = {
    .n =  28, .h = 3,
    .w = 3, .c = 3
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_0_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 28
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_0_output_dims = {
    .n = 1, .h = 32,
    .w = 32, .c = 28
};


// Quantization parameters (per-channel quantization)
static const int32_t conv_2d_0_multiplier[28] = {
    2106526286, 1321933572, 1082193469, 1670759326, 1211721976, 1322541865, 1263096265, 1295853699,
    1382985632, 1667607206, 1540022466, 1881589962, 1225978451, 1080767541, 1890510151, 2068595700,
    1417819941, 1486279737, 1488861356, 1508841935, 2114459812, 1463668338, 1400627704, 1088690684,
    1466316463, 1114309591, 1590985926, 2071195746
};

static const int32_t conv_2d_0_shift[28] = {
    -9, -9, -8, -9, -9, -9, -10, -9,
    -8, -10, -10, -9, -9, -10, -8, -10,
    -9, -8, -10, -9, -11, -10, -8, -7,
    -8, -9, -10, -11
};

static const int32_t conv_2d_0_input_zero_point = -128;
static const int32_t conv_2d_0_output_zero_point = -128;


// Scratch buffer context
static cmsis_nn_context conv_2d_0_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context conv_2d_0_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_per_channel_quant_params conv_2d_0_quant_params = {
    .multiplier = (int32_t*)conv_2d_0_multiplier,
    .shift = (int32_t*)conv_2d_0_shift,
};

const cmsis_nn_conv_params conv_2d_0_params = {
    .input_offset = -conv_2d_0_input_zero_point,
    .output_offset = conv_2d_0_output_zero_point,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
resnet_conv_2d_0_init(
    resnet_model_context_t *ctx
) {

    conv_2d_0_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_0_scratch];
    conv_2d_0_ctx.size = 128;

    conv_2d_0_weight_sum_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_0_weight_sum];
    conv_2d_0_weight_sum_ctx.size = 112;

    return ARM_CMSIS_NN_SUCCESS;

}

int32_t
resnet_conv_2d_0_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    // Bias pointer
    const int32_t *conv_2d_0_bias_ptr = NULL;

    return arm_convolve_s8(
        &conv_2d_0_ctx,
        &conv_2d_0_weight_sum_ctx,
        &conv_2d_0_params,
        &conv_2d_0_quant_params,
        &conv_2d_0_input_dims,
        input,
        &conv_2d_0_filter_dims,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_21],
        &conv_2d_0_bias_dims,
        conv_2d_0_bias_ptr,
        NULL,
        &conv_2d_0_output_dims,
        output
    );

}