/******************************************************************************
 * @file        resnet_context.c
 * @brief       heliaAOT model context API
 * @details     Defines and initializes the model context:
 *              - Assigns arena buffers & sizes
 *              - Registers callback & user_data
 *              - Populates tensor pointer arrays
 *              - Performs context-level validation
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_context.h"

int32_t resnet_context_init(
    resnet_model_context_t *ctx
) {
    if (ctx == NULL) {
        return resnet_status_null_context;
    }

    // Clear the lifecycle latch so that a stale init-success from a
    // previous lifetime cannot mask an incomplete re-init.
    ctx->_lifecycle_state = 0;

    // Wire up internal arena buffers
    ctx->arena_buffers = resnet_arena_buffers;
    ctx->arena_sizes = resnet_arena_sizes;

    // Resolve every tensor pointer through the unified arena model:
    // ``arena_buffers[region] + offset``. Cold-constant regions point
    // at a read-only blob; staged-constant and writable regions
    // point at runtime buffers.
    for (int i = 0; i < resnet_num_tensors; ++i) {
        const resnet_tensor_descriptor_t *desc = &resnet_tensor_descriptors[i];
        ctx->tensor_ptrs[i] = (int8_t *)ctx->arena_buffers[desc->region] + desc->offset;
    }

    // Wire up inputs and outputs
    for (int i = 0; i < resnet_num_inputs; ++i) {
        resnet_tensor_ident_t id = resnet_inputs_id[i];
        ctx->inputs[i].id         = id;
        ctx->inputs[i].data       = ctx->tensor_ptrs[id];
        ctx->inputs[i].size       = (size_t)resnet_inputs_len[i];
        ctx->inputs[i].zero_point = resnet_inputs_zero_point[i];
        ctx->inputs[i].scale      = resnet_inputs_scale[i];
    }

    for (int i = 0; i < resnet_num_outputs; ++i) {
        resnet_tensor_ident_t id = resnet_outputs_id[i];
        ctx->outputs[i].id         = id;
        ctx->outputs[i].data       = ctx->tensor_ptrs[id];
        ctx->outputs[i].size       = (size_t)resnet_outputs_len[i];
        ctx->outputs[i].zero_point = resnet_outputs_zero_point[i];
        ctx->outputs[i].scale      = resnet_outputs_scale[i];
    }

    return 0;
}