/******************************************************************************
 * @file        resnet_conv_2d_4.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '4' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_conv_2d_4.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_4_input_dims = {
    .n = 1, .h = 32,
    .w = 32, .c = 28
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_4_filter_dims = {
    .n =  56, .h = 3,
    .w = 3, .c = 28
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_4_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 56
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_4_output_dims = {
    .n = 1, .h = 16,
    .w = 16, .c = 56
};


// Quantization parameters (per-channel quantization)
static const int32_t conv_2d_4_multiplier[56] = {
    1956189914, 1213598677, 1199348084, 1988130025, 1584425213, 1278836105, 1546793483, 1176749965,
    1098354495, 1730500160, 1939524048, 1756292441, 1247372441, 1505690889, 1739393513, 1385134553,
    1136392810, 1803080046, 1957816661, 2052008871, 1387200854, 1093871063, 1973830838, 1224014017,
    1091600197, 1100367246, 1224020350, 1935159899, 1156759020, 1939027640, 1418203627, 1727574575,
    1776488777, 1336162671, 1080925158, 1669554195, 2086831341, 2013695577, 2075825432, 1882641166,
    1579141072, 1608359200, 1155376209, 1584812731, 1245882804, 1866758319, 1694770913, 1984616901,
    1696946379, 1395841185, 1776090247, 2081186939, 1573320188, 1601346855, 2138743262, 1748356661
};

static const int32_t conv_2d_4_shift[56] = {
    -9, -9, -8, -9, -9, -8, -8, -8,
    -8, -9, -9, -9, -8, -8, -9, -8,
    -8, -9, -8, -9, -9, -8, -9, -8,
    -8, -8, -8, -9, -8, -9, -8, -9,
    -9, -8, -8, -8, -9, -8, -9, -9,
    -9, -9, -8, -9, -8, -9, -9, -9,
    -9, -8, -9, -9, -9, -9, -8, -8
};

static const int32_t conv_2d_4_input_zero_point = -128;
static const int32_t conv_2d_4_output_zero_point = -128;


// Scratch buffer context
static cmsis_nn_context conv_2d_4_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context conv_2d_4_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_per_channel_quant_params conv_2d_4_quant_params = {
    .multiplier = (int32_t*)conv_2d_4_multiplier,
    .shift = (int32_t*)conv_2d_4_shift,
};

const cmsis_nn_conv_params conv_2d_4_params = {
    .input_offset = -conv_2d_4_input_zero_point,
    .output_offset = conv_2d_4_output_zero_point,
    .stride.w = 2,
    .stride.h = 2,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
resnet_conv_2d_4_init(
    resnet_model_context_t *ctx
) {

    conv_2d_4_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_4_scratch];
    conv_2d_4_ctx.size = 1024;

    conv_2d_4_weight_sum_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_4_weight_sum];
    conv_2d_4_weight_sum_ctx.size = 224;

    return ARM_CMSIS_NN_SUCCESS;

}

int32_t
resnet_conv_2d_4_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    // Bias pointer
    const int32_t *conv_2d_4_bias_ptr = NULL;

    return arm_convolve_s8(
        &conv_2d_4_ctx,
        &conv_2d_4_weight_sum_ctx,
        &conv_2d_4_params,
        &conv_2d_4_quant_params,
        &conv_2d_4_input_dims,
        input,
        &conv_2d_4_filter_dims,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_15],
        &conv_2d_4_bias_dims,
        conv_2d_4_bias_ptr,
        NULL,
        &conv_2d_4_output_dims,
        output
    );

}