/******************************************************************************
 * @file        resnet_conv_2d_6.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '6' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_conv_2d_6.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_6_input_dims = {
    .n = 1, .h = 32,
    .w = 32, .c = 28
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_6_filter_dims = {
    .n =  56, .h = 1,
    .w = 1, .c = 28
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_6_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 56
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_6_output_dims = {
    .n = 1, .h = 16,
    .w = 16, .c = 56
};


// Quantization parameters (per-channel quantization)
static const int32_t conv_2d_6_multiplier[56] = {
    1631758943, 1768822559, 1127734376, 1205757484, 1160788592, 1204170426, 1867131183, 2015135178,
    1740993535, 1379985208, 1179329413, 1452267062, 1684841579, 1926621832, 1681603590, 1867621712,
    1629349533, 1721238580, 1950110288, 1289569883, 1312874991, 1552306416, 1510830652, 1428623993,
    1686477921, 1106273689, 1098473265, 1347867837, 1493411803, 2046959602, 1791627797, 2124081716,
    1464026236, 1651614246, 1598584808, 1549617136, 2139933078, 1561024203, 1500560680, 1111931942,
    1145812246, 2001925768, 1738957404, 1825297086, 1665279846, 1421938957, 1150521822, 1355577522,
    1840820006, 1117059722, 1490274250, 1297953801, 1980203181, 1731576873, 1476531611, 1173628103
};

static const int32_t conv_2d_6_shift[56] = {
    -10, -9, -9, -9, -9, -10, -10, -10,
    -10, -9, -9, -10, -10, -10, -10, -9,
    -10, -10, -10, -9, -9, -10, -10, -9,
    -10, -9, -10, -10, -10, -10, -10, -10,
    -10, -10, -10, -10, -10, -10, -9, -9,
    -9, -10, -10, -10, -10, -10, -9, -10,
    -10, -9, -10, -9, -10, -10, -9, -9
};

static const int32_t conv_2d_6_input_zero_point = -128;
static const int32_t conv_2d_6_output_zero_point = -76;


// Scratch buffer context
static cmsis_nn_context conv_2d_6_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context conv_2d_6_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_per_channel_quant_params conv_2d_6_quant_params = {
    .multiplier = (int32_t*)conv_2d_6_multiplier,
    .shift = (int32_t*)conv_2d_6_shift,
};

const cmsis_nn_conv_params conv_2d_6_params = {
    .input_offset = -conv_2d_6_input_zero_point,
    .output_offset = conv_2d_6_output_zero_point,
    .stride.w = 2,
    .stride.h = 2,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
resnet_conv_2d_6_init(
    resnet_model_context_t *ctx
) {

    conv_2d_6_ctx.buf = NULL;
    conv_2d_6_ctx.size = 0;

    conv_2d_6_weight_sum_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_6_weight_sum];
    conv_2d_6_weight_sum_ctx.size = 224;

    return ARM_CMSIS_NN_SUCCESS;

}

int32_t
resnet_conv_2d_6_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    // Bias pointer
    const int32_t *conv_2d_6_bias_ptr = NULL;

    return arm_convolve_1x1_s8(
        &conv_2d_6_ctx,
        &conv_2d_6_weight_sum_ctx,
        &conv_2d_6_params,
        &conv_2d_6_quant_params,
        &conv_2d_6_input_dims,
        input,
        &conv_2d_6_filter_dims,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_11],
        &conv_2d_6_bias_dims,
        conv_2d_6_bias_ptr,
        &conv_2d_6_output_dims,
        output
    );

}