/******************************************************************************
 * @file        resnet_add_7.c
 * @brief       Autogenerated AOT add kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '7' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_add_7.h"

// Input1 dimensions
static const cmsis_nn_dims add_7_input1_dims = {
    .n = 1, .h = 16,
    .w = 16, .c = 56
};

// Input2 dimensions
static const cmsis_nn_dims add_7_input2_dims = {
    .n = 1, .h = 16,
    .w = 16, .c = 56
};

// Output dimensions
static const cmsis_nn_dims add_7_output_dims = {
    .n = 1, .h = 16,
    .w = 16, .c = 56
};

// Input quantization parameters
static const int32_t add_7_input1_zero_point = -76;
static const int32_t add_7_input1_multiplier = 1235812697;
static const int32_t add_7_input1_shift = -1;

static const int32_t add_7_input2_zero_point = -1;
static const int32_t add_7_input2_multiplier = 1073741824;
static const int32_t add_7_input2_shift = 0;

static const int32_t add_7_left_shift = 20;

// Output quantization parameters
static const int32_t add_7_output_zero_point = -128;
static const int32_t add_7_output_multiplier = 1170124909;
static const int32_t add_7_output_shift = -17;

// Activation parameters
static const int32_t add_7_activation_min = -128;
static const int32_t add_7_activation_max = 127;


int32_t
resnet_add_7_init(
    resnet_model_context_t *ctx
) {
    return 0;
}

int32_t
resnet_add_7_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input1,
    const int8_t* __restrict input2,
    int8_t* __restrict output
) {

    return arm_add_s8(
        input1,
        &add_7_input1_dims,
        input2,
        &add_7_input2_dims,
        -add_7_input1_zero_point,
        add_7_input1_multiplier,
        add_7_input1_shift,
        -add_7_input2_zero_point,
        add_7_input2_multiplier,
        add_7_input2_shift,
        add_7_left_shift,
        output,
        &add_7_output_dims,
        add_7_output_zero_point,
        add_7_output_multiplier,
        add_7_output_shift,
        add_7_activation_min,
        add_7_activation_max
    );

}