/******************************************************************************
 * @file        resnet_conv_2d_2.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '2' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_conv_2d_2.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_2_input_dims = {
    .n = 1, .h = 32,
    .w = 32, .c = 28
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_2_filter_dims = {
    .n =  28, .h = 3,
    .w = 3, .c = 28
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_2_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 28
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_2_output_dims = {
    .n = 1, .h = 32,
    .w = 32, .c = 28
};


// Quantization parameters (per-channel quantization)
static const int32_t conv_2d_2_multiplier[28] = {
    1936488662, 1189060370, 1284367740, 1693216367, 1102933560, 1672649288, 1372067971, 1286240133,
    1487955659, 1229049627, 1359812987, 1956276398, 1715532672, 1955248832, 1838514032, 1662066147,
    1131190914, 1249287554, 1122625947, 1809890648, 1936880618, 1300157898, 1939541100, 2002157059,
    1177185049, 1324695921, 2088723027, 1292316404
};

static const int32_t conv_2d_2_shift[28] = {
    -10, -9, -9, -10, -9, -10, -9, -9,
    -9, -9, -9, -10, -9, -9, -9, -10,
    -9, -8, -9, -9, -10, -9, -10, -10,
    -9, -9, -9, -9
};

static const int32_t conv_2d_2_input_zero_point = -128;
static const int32_t conv_2d_2_output_zero_point = 15;


// Scratch buffer context
static cmsis_nn_context conv_2d_2_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context conv_2d_2_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_per_channel_quant_params conv_2d_2_quant_params = {
    .multiplier = (int32_t*)conv_2d_2_multiplier,
    .shift = (int32_t*)conv_2d_2_shift,
};

const cmsis_nn_conv_params conv_2d_2_params = {
    .input_offset = -conv_2d_2_input_zero_point,
    .output_offset = conv_2d_2_output_zero_point,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
resnet_conv_2d_2_init(
    resnet_model_context_t *ctx
) {

    conv_2d_2_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_2_scratch];
    conv_2d_2_ctx.size = 1024;

    conv_2d_2_weight_sum_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_2_weight_sum];
    conv_2d_2_weight_sum_ctx.size = 112;

    return ARM_CMSIS_NN_SUCCESS;

}

int32_t
resnet_conv_2d_2_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    // Bias pointer
    const int32_t *conv_2d_2_bias_ptr = NULL;

    return arm_convolve_s8(
        &conv_2d_2_ctx,
        &conv_2d_2_weight_sum_ctx,
        &conv_2d_2_params,
        &conv_2d_2_quant_params,
        &conv_2d_2_input_dims,
        input,
        &conv_2d_2_filter_dims,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_17],
        &conv_2d_2_bias_dims,
        conv_2d_2_bias_ptr,
        NULL,
        &conv_2d_2_output_dims,
        output
    );

}