/******************************************************************************
 * @file        resnet_model.c
 * @brief       Autogenerated heliaAOT model
 * @details     Model: model - MLIR Converted.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_operators.h"
#include "resnet_model.h"


int32_t resnet_model_init(
    resnet_model_context_t *ctx
) {
    if (ctx == NULL) {
        return resnet_status_null_context;
    }
    int32_t status = 0;

    status = resnet_context_init(ctx);
    if (status != 0) {
        return status;
    }

    // Initializing operator 0 (conv_2d_0)
    if (ctx->callback) { ctx->callback(0, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_conv_2d_0_init(ctx);
    if (ctx->callback) { ctx->callback(0, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 1 (conv_2d_1)
    if (ctx->callback) { ctx->callback(1, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_conv_2d_1_init(ctx);
    if (ctx->callback) { ctx->callback(1, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 2 (conv_2d_2)
    if (ctx->callback) { ctx->callback(2, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_conv_2d_2_init(ctx);
    if (ctx->callback) { ctx->callback(2, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 3 (add_3)
    if (ctx->callback) { ctx->callback(3, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_add_3_init(ctx);
    if (ctx->callback) { ctx->callback(3, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 4 (conv_2d_4)
    if (ctx->callback) { ctx->callback(4, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_conv_2d_4_init(ctx);
    if (ctx->callback) { ctx->callback(4, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 5 (conv_2d_5)
    if (ctx->callback) { ctx->callback(5, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_conv_2d_5_init(ctx);
    if (ctx->callback) { ctx->callback(5, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 6 (conv_2d_6)
    if (ctx->callback) { ctx->callback(6, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_conv_2d_6_init(ctx);
    if (ctx->callback) { ctx->callback(6, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 7 (add_7)
    if (ctx->callback) { ctx->callback(7, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_add_7_init(ctx);
    if (ctx->callback) { ctx->callback(7, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 8 (conv_2d_8)
    if (ctx->callback) { ctx->callback(8, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_conv_2d_8_init(ctx);
    if (ctx->callback) { ctx->callback(8, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 9 (conv_2d_9)
    if (ctx->callback) { ctx->callback(9, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_conv_2d_9_init(ctx);
    if (ctx->callback) { ctx->callback(9, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 10 (conv_2d_10)
    if (ctx->callback) { ctx->callback(10, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_conv_2d_10_init(ctx);
    if (ctx->callback) { ctx->callback(10, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 11 (add_11)
    if (ctx->callback) { ctx->callback(11, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_add_11_init(ctx);
    if (ctx->callback) { ctx->callback(11, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 12 (average_pool_2d_12)
    if (ctx->callback) { ctx->callback(12, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_average_pool_2d_12_init(ctx);
    if (ctx->callback) { ctx->callback(12, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 13 (reshape_13)
    if (ctx->callback) { ctx->callback(13, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_reshape_13_init(ctx);
    if (ctx->callback) { ctx->callback(13, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 14 (fully_connected_14)
    if (ctx->callback) { ctx->callback(14, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_fully_connected_14_init(ctx);
    if (ctx->callback) { ctx->callback(14, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 15 (softmax_15)
    if (ctx->callback) { ctx->callback(15, resnet_op_state_init_started, status, ctx->user_data); }
    status = resnet_softmax_15_init(ctx);
    if (ctx->callback) { ctx->callback(15, resnet_op_state_init_finished, status, ctx->user_data); }
    if (status != 0) { return status; }


    // All operator inits succeeded — arm the lifecycle latch so
    // model_run accepts this context.
    ctx->_lifecycle_state = 1;

    return status;
}

int32_t resnet_model_run(
    resnet_model_context_t *ctx
) {
    if (ctx == NULL) {
        return resnet_status_null_context;
    }

    // Reject runs when model_init was never called or failed.
    if (ctx->_lifecycle_state != 1) {
        return resnet_status_not_initialized;
    }

    int32_t status = 0;

    // Running operator 0 (conv_2d_0)
    if (ctx->callback) { ctx->callback(0, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_conv_2d_0_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_0],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_22]
    );
    if (ctx->callback) { ctx->callback(0, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 1 (conv_2d_1)
    if (ctx->callback) { ctx->callback(1, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_conv_2d_1_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_22],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_23]
    );
    if (ctx->callback) { ctx->callback(1, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 2 (conv_2d_2)
    if (ctx->callback) { ctx->callback(2, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_conv_2d_2_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_23],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_24]
    );
    if (ctx->callback) { ctx->callback(2, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 3 (add_3)
    if (ctx->callback) { ctx->callback(3, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_add_3_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_22],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_24],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_25]
    );
    if (ctx->callback) { ctx->callback(3, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 4 (conv_2d_4)
    if (ctx->callback) { ctx->callback(4, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_conv_2d_4_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_25],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_26]
    );
    if (ctx->callback) { ctx->callback(4, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 5 (conv_2d_5)
    if (ctx->callback) { ctx->callback(5, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_conv_2d_5_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_26],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_27]
    );
    if (ctx->callback) { ctx->callback(5, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 6 (conv_2d_6)
    if (ctx->callback) { ctx->callback(6, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_conv_2d_6_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_25],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_28]
    );
    if (ctx->callback) { ctx->callback(6, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 7 (add_7)
    if (ctx->callback) { ctx->callback(7, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_add_7_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_28],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_27],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_29]
    );
    if (ctx->callback) { ctx->callback(7, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 8 (conv_2d_8)
    if (ctx->callback) { ctx->callback(8, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_conv_2d_8_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_29],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_30]
    );
    if (ctx->callback) { ctx->callback(8, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 9 (conv_2d_9)
    if (ctx->callback) { ctx->callback(9, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_conv_2d_9_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_30],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_31]
    );
    if (ctx->callback) { ctx->callback(9, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 10 (conv_2d_10)
    if (ctx->callback) { ctx->callback(10, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_conv_2d_10_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_29],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_32]
    );
    if (ctx->callback) { ctx->callback(10, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 11 (add_11)
    if (ctx->callback) { ctx->callback(11, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_add_11_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_32],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_31],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_33]
    );
    if (ctx->callback) { ctx->callback(11, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 12 (average_pool_2d_12)
    if (ctx->callback) { ctx->callback(12, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_average_pool_2d_12_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_33],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_34]
    );
    if (ctx->callback) { ctx->callback(12, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 13 (reshape_13)
    if (ctx->callback) { ctx->callback(13, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_reshape_13_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_34],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_35]
    );
    if (ctx->callback) { ctx->callback(13, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 14 (fully_connected_14)
    if (ctx->callback) { ctx->callback(14, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_fully_connected_14_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_35],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_36]
    );
    if (ctx->callback) { ctx->callback(14, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    // Running operator 15 (softmax_15)
    if (ctx->callback) { ctx->callback(15, resnet_op_state_run_started, status, ctx->user_data); }
    status = resnet_softmax_15_run(
        ctx,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_36],
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_37]
    );
    if (ctx->callback) { ctx->callback(15, resnet_op_state_run_finished, status, ctx->user_data); }
    if (status != 0) { return status; }

    return status;
}