/******************************************************************************
 * @file        resnet_tensors.c
 * @brief       Autogenerated tensor definitions
 * @details     Contains tensor definitions, arenas, and model I/O.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_tensors.h"


//── Memory Arenas ─────────────────────────────────────────────────────────────

const size_t resnet_arena_sizes[resnet_num_arena_buffers] = {
    [resnet_arena_dtcm] = resnet_arena_dtcm_size,
    [resnet_arena_const_dtcm] = resnet_arena_const_dtcm_size,
};

// Per-region alignment (bytes). Caller-supplied buffers passed to
// ``resnet_bind_arena`` must be aligned to at least this many
// bytes for the region; otherwise the bind is rejected with status
// 4. Internal arena buffers are emitted with ``alignas(...)`` matching
// these values, so ``allocate_arenas=true`` builds always satisfy the
// constraint.
const size_t resnet_arena_alignments[resnet_num_arena_buffers] = {
    [resnet_arena_dtcm] = 16,
    [resnet_arena_const_dtcm] = 16,
};

// Internal arena buffers. Writable arenas (scratch, persistent, and
// staged-constant runtime copies) are uninitialized BSS-backed
// storage; cold-constant arenas are read-only blobs whose bytes are
// initialised in resnet_constants.c.
alignas(16) static RESNET_PUT_IN_DTCM int8_t resnet_arena_dtcm_buffer[resnet_arena_dtcm_size];

extern RESNET_PUT_IN_DTCM_INIT int8_t resnet_arena_const_dtcm__blob[237912];

const void * const resnet_arena_buffers[resnet_num_arena_buffers] = {
    [resnet_arena_dtcm] = resnet_arena_dtcm_buffer,
    // Cold constant arena: kernels read directly from the in-image blob.
    [resnet_arena_const_dtcm] = resnet_arena_const_dtcm__blob,
};


//── Model Input/Output ────────────────────────────────────────────────────────

const resnet_tensor_ident_t resnet_inputs_id[resnet_num_inputs] = {
    resnet_tensor_0,
};

const resnet_tensor_ident_t resnet_outputs_id[resnet_num_outputs] = {
    resnet_tensor_37,
};

const int32_t resnet_inputs_len[resnet_num_inputs] = {
    3072,
};

const int32_t resnet_inputs_zero_point[resnet_num_inputs] = {
    -128,
};

const float resnet_inputs_scale[resnet_num_inputs] = {
    1.0,
};

const int32_t resnet_outputs_len[resnet_num_outputs] = {
    10,
};

const int32_t resnet_outputs_zero_point[resnet_num_outputs] = {
    -128,
};

const float resnet_outputs_scale[resnet_num_outputs] = {
    0.00390625,
};

//── Model Tensors ─────────────────────────────────────────────────────────────

// Tensor descriptors. Uniform shape: every tensor lives in an arena
// slot, addressed by ``(region, offset)``.
const resnet_tensor_descriptor_t resnet_tensor_descriptors[resnet_num_tensors] = {
    [resnet_tensor_0] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 0,
        .size = 3072,
    },
    [resnet_tensor_3] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 236752,
        .size = 1120,
    },
    [resnet_tensor_5] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 230032,
        .size = 6272,
    },
    [resnet_tensor_7] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 116688,
        .size = 112896,
    },
    [resnet_tensor_9] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 59792,
        .size = 56448,
    },
    [resnet_tensor_11] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 58000,
        .size = 1568,
    },
    [resnet_tensor_13] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 29552,
        .size = 28224,
    },
    [resnet_tensor_15] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 15216,
        .size = 14112,
    },
    [resnet_tensor_17] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 8048,
        .size = 7056,
    },
    [resnet_tensor_19] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 880,
        .size = 7056,
    },
    [resnet_tensor_21] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 0,
        .size = 756,
    },
    [resnet_tensor_22] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 3072,
        .size = 28672,
    },
    [resnet_tensor_23] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 31744,
        .size = 28672,
    },
    [resnet_tensor_24] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 60416,
        .size = 28672,
    },
    [resnet_tensor_25] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 31744,
        .size = 28672,
    },
    [resnet_tensor_26] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 0,
        .size = 14336,
    },
    [resnet_tensor_27] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 14336,
        .size = 14336,
    },
    [resnet_tensor_28] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 0,
        .size = 14336,
    },
    [resnet_tensor_29] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 28672,
        .size = 14336,
    },
    [resnet_tensor_30] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 0,
        .size = 7168,
    },
    [resnet_tensor_31] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 7168,
        .size = 7168,
    },
    [resnet_tensor_32] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 0,
        .size = 7168,
    },
    [resnet_tensor_33] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 14336,
        .size = 7168,
    },
    [resnet_tensor_34] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 0,
        .size = 112,
    },
    [resnet_tensor_35] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 0,
        .size = 112,
    },
    [resnet_tensor_36] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 112,
        .size = 10,
    },
    [resnet_tensor_37] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 0,
        .size = 10,
    },
    [resnet_tensor_conv_2d_0_scratch] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 31744,
        .size = 128,
    },
    [resnet_tensor_conv_2d_0_weight_sum] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 768,
        .size = 112,
    },
    [resnet_tensor_conv_2d_1_scratch] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 0,
        .size = 1024,
    },
    [resnet_tensor_conv_2d_1_weight_sum] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 7936,
        .size = 112,
    },
    [resnet_tensor_conv_2d_2_scratch] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 0,
        .size = 1024,
    },
    [resnet_tensor_conv_2d_2_weight_sum] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 15104,
        .size = 112,
    },
    [resnet_tensor_conv_2d_4_scratch] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 14336,
        .size = 1024,
    },
    [resnet_tensor_conv_2d_4_weight_sum] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 29328,
        .size = 224,
    },
    [resnet_tensor_conv_2d_5_scratch] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 28672,
        .size = 2048,
    },
    [resnet_tensor_conv_2d_5_weight_sum] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 57776,
        .size = 224,
    },
    [resnet_tensor_conv_2d_6_weight_sum] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 59568,
        .size = 224,
    },
    [resnet_tensor_conv_2d_8_scratch] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 7168,
        .size = 2048,
    },
    [resnet_tensor_conv_2d_8_weight_sum] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 116240,
        .size = 448,
    },
    [resnet_tensor_conv_2d_9_scratch] = {
        .type = resnet_tensor_type_scratch,
        .region = resnet_arena_dtcm,
        .offset = 14336,
        .size = 4032,
    },
    [resnet_tensor_conv_2d_9_weight_sum] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 229584,
        .size = 448,
    },
    [resnet_tensor_conv_2d_10_weight_sum] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 236304,
        .size = 448,
    },
    [resnet_tensor_fully_connected_14_weight_sum] = {
        .type = resnet_tensor_type_constant,
        .region = resnet_arena_const_dtcm,
        .offset = 237872,
        .size = 40,
    },
};