/******************************************************************************
 * @file        resnet_conv_2d_5.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '5' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_conv_2d_5.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_5_input_dims = {
    .n = 1, .h = 16,
    .w = 16, .c = 56
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_5_filter_dims = {
    .n =  56, .h = 3,
    .w = 3, .c = 56
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_5_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 56
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_5_output_dims = {
    .n = 1, .h = 16,
    .w = 16, .c = 56
};


// Quantization parameters (per-channel quantization)
static const int32_t conv_2d_5_multiplier[56] = {
    1573675256, 1969344893, 1285803745, 1628911103, 1828111218, 1682237189, 1388597366, 1552956173,
    1610965265, 1880804399, 1900389242, 1659103013, 2128100754, 1691952021, 2066681514, 1950727878,
    2114929696, 1808599682, 1839538169, 1738482371, 1420573273, 1087863823, 1112214115, 1819737027,
    1180344171, 2035974750, 1280700707, 1711946614, 2087567772, 1325567682, 1104748250, 1677595122,
    1998511282, 1468450357, 1291125557, 1338044429, 1526271804, 1269219967, 1621280823, 1995558105,
    1175198768, 1989396036, 1409994195, 1295798090, 1096069030, 1637221699, 1307738467, 1750537658,
    1408375278, 1104351827, 1802813853, 1785131154, 1124432198, 1869624594, 1708254475, 1652620873
};

static const int32_t conv_2d_5_shift[56] = {
    -9, -10, -9, -10, -10, -10, -9, -10,
    -10, -10, -10, -9, -10, -10, -10, -10,
    -10, -10, -10, -10, -9, -9, -9, -9,
    -9, -10, -9, -10, -10, -9, -9, -10,
    -10, -9, -9, -9, -9, -9, -9, -10,
    -9, -10, -9, -9, -9, -10, -9, -10,
    -9, -9, -10, -10, -9, -10, -10, -10
};

static const int32_t conv_2d_5_input_zero_point = -128;
static const int32_t conv_2d_5_output_zero_point = -1;


// Scratch buffer context
static cmsis_nn_context conv_2d_5_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context conv_2d_5_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_per_channel_quant_params conv_2d_5_quant_params = {
    .multiplier = (int32_t*)conv_2d_5_multiplier,
    .shift = (int32_t*)conv_2d_5_shift,
};

const cmsis_nn_conv_params conv_2d_5_params = {
    .input_offset = -conv_2d_5_input_zero_point,
    .output_offset = conv_2d_5_output_zero_point,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
resnet_conv_2d_5_init(
    resnet_model_context_t *ctx
) {

    conv_2d_5_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_5_scratch];
    conv_2d_5_ctx.size = 2048;

    conv_2d_5_weight_sum_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_5_weight_sum];
    conv_2d_5_weight_sum_ctx.size = 224;

    return ARM_CMSIS_NN_SUCCESS;

}

int32_t
resnet_conv_2d_5_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    // Bias pointer
    const int32_t *conv_2d_5_bias_ptr = NULL;

    return arm_convolve_s8(
        &conv_2d_5_ctx,
        &conv_2d_5_weight_sum_ctx,
        &conv_2d_5_params,
        &conv_2d_5_quant_params,
        &conv_2d_5_input_dims,
        input,
        &conv_2d_5_filter_dims,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_13],
        &conv_2d_5_bias_dims,
        conv_2d_5_bias_ptr,
        NULL,
        &conv_2d_5_output_dims,
        output
    );

}