/******************************************************************************
 * @file        resnet_average_pool_2d_12.c
 * @brief       Autogenerated AOT average_pool_2d kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '12' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/


#include "resnet_common.h"
#include "resnet_average_pool_2d_12.h"

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims average_pool_2d_12_input_dims = {
    .n = 1, .h = 8,
    .w = 8, .c = 112
};

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, 1].
static const cmsis_nn_dims average_pool_2d_12_filter_dims = {
    .n = 1, .h = 8,
    .w = 8, .c = 1
};

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT]. C_OUT = C_IN
static const cmsis_nn_dims average_pool_2d_12_output_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 112
};

static cmsis_nn_context average_pool_2d_12_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_pool_params average_pool_2d_12_params = {
    .stride.w = 8,
    .stride.h = 8,
    .padding.w = 0,
    .padding.h = 0,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
resnet_average_pool_2d_12_init(
    resnet_model_context_t *ctx
) {
    average_pool_2d_12_ctx.buf = NULL;
    average_pool_2d_12_ctx.size = 0;

    return 0;
}


int32_t
resnet_average_pool_2d_12_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    return arm_avgpool_s8(
        &average_pool_2d_12_ctx,
        &average_pool_2d_12_params,
        &average_pool_2d_12_input_dims,
        input,
        &average_pool_2d_12_filter_dims,
        &average_pool_2d_12_output_dims,
        output
    );

}