/******************************************************************************
 * @file        resnet_conv_2d_9.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '9' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_conv_2d_9.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_9_input_dims = {
    .n = 1, .h = 8,
    .w = 8, .c = 112
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_9_filter_dims = {
    .n =  112, .h = 3,
    .w = 3, .c = 112
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_9_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 112
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_9_output_dims = {
    .n = 1, .h = 8,
    .w = 8, .c = 112
};


// Quantization parameters (per-channel quantization)
static const int32_t conv_2d_9_multiplier[112] = {
    1375355284, 1829183951, 1519236100, 1709168628, 1336782790, 1638011236, 1183749316, 1370012143,
    1339133979, 1503487931, 1337929964, 1140373752, 1195135715, 1252026741, 2134576622, 1339689997,
    1580761958, 1256867164, 1087090343, 1416027534, 1465033550, 1202752313, 1794087231, 1105668281,
    1193207666, 1456606327, 1483787846, 1263770284, 1449787805, 1237826813, 1773293270, 1400676521,
    1211216446, 1288165809, 1419743964, 2026138746, 1512573487, 1347373993, 1678408578, 1194309735,
    1667558855, 1382071787, 1437142025, 1357676114, 1292437075, 1341221333, 1198723917, 1215726964,
    1587371125, 1528215502, 1645323471, 2058512074, 1844071666, 1410670367, 1310461874, 1393712572,
    1355360506, 1355924054, 1313214943, 1281381245, 1214998059, 1284922571, 1204130840, 1396436703,
    1236112106, 1571236579, 1660809576, 1168923832, 1368126762, 1387030175, 1430811014, 1586754575,
    1491417362, 1518091289, 1604433893, 1374398568, 1562025675, 1566593552, 1428291219, 1425685201,
    1347439841, 1387678764, 1575639245, 1712930087, 1635256543, 1145637832, 1443837857, 1750962805,
    1319410271, 1631050683, 1683467658, 1166441242, 1841784701, 1412128621, 2079816726, 1416038903,
    1706186715, 1655581595, 1865806693, 1285155549, 1744786818, 1322146509, 1717842559, 1624025905,
    1638310062, 1351556231, 1625879691, 1563406122, 1532195766, 1077533147, 1547954122, 1491312241
};

static const int32_t conv_2d_9_shift[112] = {
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -10, -9,
    -9, -9, -8, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -10, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9
};

static const int32_t conv_2d_9_input_zero_point = -128;
static const int32_t conv_2d_9_output_zero_point = 11;


// Scratch buffer context
static cmsis_nn_context conv_2d_9_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context conv_2d_9_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_per_channel_quant_params conv_2d_9_quant_params = {
    .multiplier = (int32_t*)conv_2d_9_multiplier,
    .shift = (int32_t*)conv_2d_9_shift,
};

const cmsis_nn_conv_params conv_2d_9_params = {
    .input_offset = -conv_2d_9_input_zero_point,
    .output_offset = conv_2d_9_output_zero_point,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
resnet_conv_2d_9_init(
    resnet_model_context_t *ctx
) {

    conv_2d_9_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_9_scratch];
    conv_2d_9_ctx.size = 4032;

    conv_2d_9_weight_sum_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_9_weight_sum];
    conv_2d_9_weight_sum_ctx.size = 448;

    return ARM_CMSIS_NN_SUCCESS;

}

int32_t
resnet_conv_2d_9_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    // Bias pointer
    const int32_t *conv_2d_9_bias_ptr = NULL;

    return arm_convolve_s8(
        &conv_2d_9_ctx,
        &conv_2d_9_weight_sum_ctx,
        &conv_2d_9_params,
        &conv_2d_9_quant_params,
        &conv_2d_9_input_dims,
        input,
        &conv_2d_9_filter_dims,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_7],
        &conv_2d_9_bias_dims,
        conv_2d_9_bias_ptr,
        NULL,
        &conv_2d_9_output_dims,
        output
    );

}