/******************************************************************************
 * @file        resnet_softmax_15.c
 * @brief       Autogenerated AOT softmax kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '15' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_softmax_15.h"

// Softmax parameters
static const int32_t softmax_15_num_rows = 1;
static const int32_t softmax_15_row_size = 10;
static const int32_t softmax_15_input_multiplier = 1080892288;
static const int32_t softmax_15_input_shift = 25;

static const int32_t softmax_15_diff_min = -62;

int32_t
resnet_softmax_15_init(
    resnet_model_context_t *ctx
) {
    return 0;
}

int32_t
resnet_softmax_15_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    arm_softmax_s8(
        input,
        softmax_15_num_rows,
        softmax_15_row_size,
        softmax_15_input_multiplier,
        softmax_15_input_shift,
        softmax_15_diff_min,
        output
    );

    return 0;

}