/******************************************************************************
 * @file        resnet_conv_2d_1.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '1' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_conv_2d_1.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_1_input_dims = {
    .n = 1, .h = 32,
    .w = 32, .c = 28
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_1_filter_dims = {
    .n =  28, .h = 3,
    .w = 3, .c = 28
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_1_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 28
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_1_output_dims = {
    .n = 1, .h = 32,
    .w = 32, .c = 28
};


// Quantization parameters (per-channel quantization)
static const int32_t conv_2d_1_multiplier[28] = {
    1283719873, 1648835888, 1327198371, 1662437997, 1520975768, 1417329784, 1233414741, 1219461263,
    1430980615, 1729342387, 1095623488, 1183603408, 1286111972, 1625224609, 1952254539, 1415212153,
    1358056270, 1175289528, 2071518758, 1303565248, 1661218480, 1526895519, 1205764957, 1123552206,
    2124740322, 1834410735, 1664951090, 1212857614
};

static const int32_t conv_2d_1_shift[28] = {
    -7, -8, -8, -9, -8, -8, -8, -8,
    -8, -9, -8, -9, -8, -9, -9, -8,
    -8, -9, -9, -8, -8, -8, -8, -7,
    -9, -9, -9, -8
};

static const int32_t conv_2d_1_input_zero_point = -128;
static const int32_t conv_2d_1_output_zero_point = -128;


// Scratch buffer context
static cmsis_nn_context conv_2d_1_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context conv_2d_1_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_per_channel_quant_params conv_2d_1_quant_params = {
    .multiplier = (int32_t*)conv_2d_1_multiplier,
    .shift = (int32_t*)conv_2d_1_shift,
};

const cmsis_nn_conv_params conv_2d_1_params = {
    .input_offset = -conv_2d_1_input_zero_point,
    .output_offset = conv_2d_1_output_zero_point,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 1,
    .padding.h = 1,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
resnet_conv_2d_1_init(
    resnet_model_context_t *ctx
) {

    conv_2d_1_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_1_scratch];
    conv_2d_1_ctx.size = 1024;

    conv_2d_1_weight_sum_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_1_weight_sum];
    conv_2d_1_weight_sum_ctx.size = 112;

    return ARM_CMSIS_NN_SUCCESS;

}

int32_t
resnet_conv_2d_1_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    // Bias pointer
    const int32_t *conv_2d_1_bias_ptr = NULL;

    return arm_convolve_s8(
        &conv_2d_1_ctx,
        &conv_2d_1_weight_sum_ctx,
        &conv_2d_1_params,
        &conv_2d_1_quant_params,
        &conv_2d_1_input_dims,
        input,
        &conv_2d_1_filter_dims,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_19],
        &conv_2d_1_bias_dims,
        conv_2d_1_bias_ptr,
        NULL,
        &conv_2d_1_output_dims,
        output
    );

}