/******************************************************************************
 * @file        resnet_conv_2d_8.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.17.1 on 2026-06-09.
 *              This kernel represents node '8' in the corresponding graph.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "resnet_common.h"
#include "resnet_conv_2d_8.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_8_input_dims = {
    .n = 1, .h = 16,
    .w = 16, .c = 56
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_8_filter_dims = {
    .n =  112, .h = 3,
    .w = 3, .c = 56
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_8_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 112
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_8_output_dims = {
    .n = 1, .h = 8,
    .w = 8, .c = 112
};


// Quantization parameters (per-channel quantization)
static const int32_t conv_2d_8_multiplier[112] = {
    1483439071, 2001517462, 1687501139, 1814115893, 1627182275, 1343517498, 1757505051, 2127095776,
    2083011979, 1179227559, 1277132171, 1473597892, 1519597669, 2030475808, 1732030804, 1240807554,
    2034225143, 1793447197, 1202952285, 1661927456, 1839878448, 1106124216, 1720911023, 1428910558,
    1444525827, 1246153905, 1558765491, 1574282312, 1396180573, 1394825829, 1612084623, 1222485104,
    1430532626, 1719683623, 1750518174, 1976079913, 1346266432, 1117681954, 1077005015, 2042009704,
    1435355318, 1462105200, 1418314766, 1658585424, 1810340738, 1479695780, 1511292087, 1415258296,
    1211037900, 1223389476, 1746295174, 1275862799, 1547772285, 1777999267, 1514680485, 1541901616,
    1350637762, 1170634766, 1489102847, 1754423749, 1262316235, 1083615574, 1225690344, 2139568653,
    1575154601, 1104164287, 1683398560, 1451634114, 1129882234, 1414574661, 1594127943, 1823073576,
    1460285030, 1851227206, 1171906446, 1569815722, 1398228182, 1282840446, 1186657337, 2140895929,
    1560188357, 1613745695, 1333576444, 1273628405, 1319738275, 1172858173, 1556960594, 1918027637,
    1774613065, 1325739034, 1543928679, 1977571121, 2097045724, 1363259188, 1079835804, 1289662732,
    1532807579, 1582134995, 1903253562, 1196538839, 1420118125, 1701928122, 1405813432, 1194953690,
    1352786345, 1351340295, 1979319653, 1380399505, 1413843011, 1722360369, 1266123363, 1773579812
};

static const int32_t conv_2d_8_shift[112] = {
    -9, -10, -9, -9, -9, -9, -9, -9,
    -10, -9, -9, -8, -9, -10, -9, -8,
    -10, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -10, -9, -9, -9, -9, -10,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -10, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -8, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -10,
    -9, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -10, -9, -9, -9,
    -8, -9, -9, -9, -9, -9, -9, -9,
    -9, -9, -9, -9, -9, -9, -9, -9
};

static const int32_t conv_2d_8_input_zero_point = -128;
static const int32_t conv_2d_8_output_zero_point = -128;


// Scratch buffer context
static cmsis_nn_context conv_2d_8_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context conv_2d_8_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_per_channel_quant_params conv_2d_8_quant_params = {
    .multiplier = (int32_t*)conv_2d_8_multiplier,
    .shift = (int32_t*)conv_2d_8_shift,
};

const cmsis_nn_conv_params conv_2d_8_params = {
    .input_offset = -conv_2d_8_input_zero_point,
    .output_offset = conv_2d_8_output_zero_point,
    .stride.w = 2,
    .stride.h = 2,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
resnet_conv_2d_8_init(
    resnet_model_context_t *ctx
) {

    conv_2d_8_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_8_scratch];
    conv_2d_8_ctx.size = 2048;

    conv_2d_8_weight_sum_ctx.buf = ctx->tensor_ptrs[resnet_tensor_conv_2d_8_weight_sum];
    conv_2d_8_weight_sum_ctx.size = 448;

    return ARM_CMSIS_NN_SUCCESS;

}

int32_t
resnet_conv_2d_8_run(
    resnet_model_context_t *ctx,
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    // Bias pointer
    const int32_t *conv_2d_8_bias_ptr = NULL;

    return arm_convolve_s8(
        &conv_2d_8_ctx,
        &conv_2d_8_weight_sum_ctx,
        &conv_2d_8_params,
        &conv_2d_8_quant_params,
        &conv_2d_8_input_dims,
        input,
        &conv_2d_8_filter_dims,
        (int8_t *)ctx->tensor_ptrs[resnet_tensor_9],
        &conv_2d_8_bias_dims,
        conv_2d_8_bias_ptr,
        NULL,
        &conv_2d_8_output_dims,
        output
    );

}