"""Atomic IO helpers for ``nsx.lock`` files."""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

import yaml

from ._constants import LOCK_FILENAME
from ._models import NsxLock


def lock_path(app_dir: Path) -> Path:
    return app_dir / LOCK_FILENAME


def read_lock(app_dir: Path) -> NsxLock | None:
    """Read nsx.lock from *app_dir*, or return ``None`` if missing.

    Raises :class:`NSXLockError` if the on-disk file uses a schema
    other than :data:`LOCK_SCHEMA_VERSION` so callers like ``nsx sync``
    / ``nsx outdated`` fail loudly with the upgrade hint. ``nsx lock``
    catches this and regenerates the file in place.
    """

    path = lock_path(app_dir)
    if not path.exists():
        return None
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    lock = NsxLock.from_yaml_dict(raw or {})
    lock.path = path
    return lock


def write_lock(app_dir: Path, lock: NsxLock) -> Path:
    """Write *lock* to ``<app_dir>/nsx.lock`` atomically and return the path.

    Writes through a same-directory temp file + ``os.replace`` so a
    crash or Ctrl-C mid-write cannot leave a half-written ``nsx.lock``
    on disk. ``os.replace`` is atomic on POSIX and Windows when both
    paths are on the same filesystem (guaranteed here because the temp
    file lives next to the target).
    """

    path = lock_path(app_dir)
    text = yaml.safe_dump(lock.to_yaml_dict(), sort_keys=False, default_flow_style=False)
    header = (
        "# nsx.lock — generated by `nsx lock`. Do not edit by hand.\n"
        "# Commit this file to record the resolved module set for this app.\n"
    )
    payload = (header + text).encode("utf-8")

    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(payload)
            fh.flush()
            try:
                os.fsync(fh.fileno())
            except OSError:
                # fsync can fail on some filesystems (e.g. tmpfs in
                # CI); the os.replace below is still atomic.
                pass
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise
    lock.path = path
    return path
