"""Atomic IO helpers for ``nsx.lock`` files."""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

import yaml

from .._errors import NSXLockError
from ._constants import LOCK_FILENAME
from ._models import LockFile, NsxLock


def lock_path(app_dir: Path) -> Path:
    """Path to the app's single combined lock file ``nsx.lock``.

    Every app — single- or multi-target — keeps one ``nsx.lock`` whose
    ``targets`` map records a resolution section per board, so the app
    root holds exactly one manifest and one lock.
    """

    return app_dir / LOCK_FILENAME


def read_lock_file(app_dir: Path) -> LockFile | None:
    """Read the combined :class:`LockFile` for *app_dir*, or ``None``.

    Raises :class:`NSXLockError` when the on-disk file uses a schema
    other than :data:`LOCK_SCHEMA_VERSION` so callers like ``nsx sync``
    / ``nsx outdated`` fail loudly with the upgrade hint. ``nsx lock``
    catches this and regenerates the file in place.
    """

    path = lock_path(app_dir)
    if not path.exists():
        return None
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    lock_file = LockFile.from_yaml_dict(raw or {})
    lock_file.path = path
    return lock_file


def read_lock(app_dir: Path, board: str | None = None) -> NsxLock | None:
    """Read the per-board resolution section from the app's ``nsx.lock``.

    When *board* is ``None`` (e.g. a read-only caller whose manifest is
    unreadable) the sole target is returned if the lock has exactly one;
    otherwise ``None`` (ambiguous). Returns ``None`` if the lock file or
    the requested board's section is missing.
    """

    lock_file = read_lock_file(app_dir)
    if lock_file is None:
        return None
    if board is None:
        if len(lock_file.targets) == 1:
            lock = next(iter(lock_file.targets.values()))
        else:
            return None
    else:
        lock = lock_file.targets.get(board)
        if lock is None:
            return None
    lock.path = lock_file.path
    return lock


def _atomic_write(path: Path, payload: bytes) -> None:
    """Atomically write *payload* to *path* via temp file + ``os.replace``."""

    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(payload)
            fh.flush()
            try:
                os.fsync(fh.fileno())
            except OSError:
                # fsync can fail on some filesystems (e.g. tmpfs in
                # CI); the os.replace below is still atomic.
                pass
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


_HEADER = (
    "# nsx.lock — generated by `nsx lock`. Do not edit by hand.\n"
    "# Commit this file to record the resolved module set for this app.\n"
)


def _write_lock_file(app_dir: Path, lock_file: LockFile) -> Path:
    path = lock_path(app_dir)
    text = yaml.safe_dump(lock_file.to_yaml_dict(), sort_keys=False, default_flow_style=False)
    _atomic_write(path, (_HEADER + text).encode("utf-8"))
    lock_file.path = path
    return path


def write_lock(app_dir: Path, lock: NsxLock, board: str | None = None) -> Path:
    """Write *lock* into the app's combined ``nsx.lock`` and return its path.

    Read-modify-write: the existing lock file is loaded and only the
    *board* section is replaced, so sibling targets are preserved when
    a single board is re-locked. When *board* is ``None`` the board key
    is taken from ``lock.target['board']``. A stale / unreadable
    on-disk lock (e.g. an older schema) is discarded and rebuilt.

    The read-modify-write is not atomic across the read and the write, so
    callers writing multiple boards of the same app concurrently must hold
    the per-app advisory lock (``app_lock(app_dir)``) around the writes;
    ``lock_app_impl`` already does this for its whole board loop.
    """

    if board is None:
        board = str(lock.target.get("board") or "")
    if not board:
        raise NSXLockError(
            "write_lock requires a board key (none supplied and lock.target "
            "has no 'board')."
        )

    existing: LockFile | None = None
    if lock_path(app_dir).exists():
        try:
            existing = read_lock_file(app_dir)
        except (NSXLockError, yaml.YAMLError, ValueError):
            # Stale / unreadable / old-schema lock: start fresh.
            existing = None
    lock_file = existing or LockFile()
    lock_file.targets[board] = lock
    path = _write_lock_file(app_dir, lock_file)
    lock.path = path
    return path


def prune_lock_targets(app_dir: Path, keep: set[str]) -> None:
    """Drop any lock sections whose board is not in *keep*.

    Used after a full ``nsx lock`` so a board removed from ``targets:``
    in ``nsx.yml`` does not leave an orphaned section behind. No-op when
    the lock is missing/unreadable or already pruned.
    """

    try:
        lock_file = read_lock_file(app_dir)
    except (NSXLockError, ValueError):
        return
    if lock_file is None:
        return
    removed = [b for b in lock_file.targets if b not in keep]
    if not removed:
        return
    for board in removed:
        del lock_file.targets[board]
    _write_lock_file(app_dir, lock_file)
