"""Phase 5: gitignore the regenerated ``cmake/nsx/`` build-glue tree.

The whole ``cmake/nsx/`` directory is reproduced from the pinned
``neuralspotx`` package on every ``nsx lock`` / ``nsx sync``, so apps must
not commit it. The ignore rule lives in the app-owned ``cmake/.gitignore``
(the parent dir) so it never perturbs the content hash of the regenerated
tooling tree.
"""

from __future__ import annotations

from pathlib import Path

from neuralspotx.operations import create_app_impl
from neuralspotx.project_config import _write_cmake_nsx_gitignore


def test_helper_writes_cmake_gitignore(tmp_path: Path) -> None:
    _write_cmake_nsx_gitignore(tmp_path)
    gitignore = tmp_path / "cmake" / ".gitignore"
    assert gitignore.is_file()
    lines = gitignore.read_text(encoding="utf-8").splitlines()
    assert "/nsx/" in lines
    assert lines[0].startswith("# Auto-generated by neuralspotx")


def test_helper_does_not_write_inside_nsx_tree(tmp_path: Path) -> None:
    _write_cmake_nsx_gitignore(tmp_path)
    # Nothing is written inside cmake/nsx/, so the hashed tooling tree is
    # never perturbed by the ignore rule.
    assert not (tmp_path / "cmake" / "nsx" / ".gitignore").exists()


def test_helper_is_idempotent(tmp_path: Path) -> None:
    _write_cmake_nsx_gitignore(tmp_path)
    first = (tmp_path / "cmake" / ".gitignore").read_text(encoding="utf-8")
    _write_cmake_nsx_gitignore(tmp_path)
    second = (tmp_path / "cmake" / ".gitignore").read_text(encoding="utf-8")
    assert first == second
    # The /nsx/ rule line appears exactly once (ignore comment lines that
    # merely mention the path).
    rule_lines = [ln for ln in second.splitlines() if ln.strip() == "/nsx/"]
    assert len(rule_lines) == 1


def test_helper_preserves_existing_user_gitignore(tmp_path: Path) -> None:
    cmake_dir = tmp_path / "cmake"
    cmake_dir.mkdir()
    (cmake_dir / ".gitignore").write_text("build/\n*.user\n", encoding="utf-8")
    _write_cmake_nsx_gitignore(tmp_path)
    text = (cmake_dir / ".gitignore").read_text(encoding="utf-8")
    assert "build/" in text
    assert "*.user" in text
    assert "/nsx/" in text


def test_create_app_emits_cmake_gitignore(tmp_path: Path) -> None:
    app_dir = tmp_path / "app"
    create_app_impl(
        app_dir,
        board="apollo510_evb",
        soc="apollo510",
        no_bootstrap=True,
    )
    gitignore = app_dir / "cmake" / ".gitignore"
    assert gitignore.is_file()
    assert "/nsx/" in gitignore.read_text(encoding="utf-8").splitlines()
    # The regenerated tooling tree is present but ignored via the rule above.
    assert (app_dir / "cmake" / "nsx" / "nsx_app_bootstrap.cmake").is_file()
