"""Prove the committed module and board snapshots still describe this tree.

``astro-site/src/data/modules.json`` and ``boards.json`` are generated by
``scripts/docs/build_module_data.py`` and committed, because the module
manifests live in other repositories and the site build is not allowed to
fetch them. A committed artifact is only worth having if something fails when
it drifts, so this module checks two things.

The snapshot is checked against the tree it claims to describe: every module in
the registry lock is in it, every board descriptor the package ships is in it,
in the package's own order, and every value is the shape the site renders.
That part needs no network.

The drift check itself is checked by mutation. ``--check`` regenerates the
snapshot and compares it with the committed one, so the comparison is the thing
that has to be trusted; each test here feeds it a snapshot that differs in one
way a real change would and asserts that it says so.
"""

from __future__ import annotations

import copy
import importlib
import json
import sys
from pathlib import Path
from typing import Any

import pytest
import yaml

from neuralspotx import list_modules
from neuralspotx.board_descriptors import load_board_descriptors
from neuralspotx.constants import BOARDS
from neuralspotx.metadata import ModuleType

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = REPO_ROOT / "scripts" / "docs"
SITE = REPO_ROOT / "astro-site"
MODULES_SNAPSHOT = SITE / "src" / "data" / "modules.json"
BOARDS_SNAPSHOT = SITE / "src" / "data" / "boards.json"
REGISTRY_LOCK = REPO_ROOT / "src" / "neuralspotx" / "data" / "registry.lock.yaml"

MODULE_TYPES = {member.value for member in ModuleType}

# Every key the site's generator reads off a module. A field added to the
# snapshot without a renderer is harmless; a field removed from under one is
# not, so the set is exact rather than a subset.
MODULE_KEYS = {
    "name",
    "slug",
    "project",
    "revision",
    "metadata_path",
    "repo_url",
    "source_url",
    "manifest_source",
    "manifest_error",
    "type",
    "category",
    "provider",
    "version",
    "summary",
    "capabilities",
    "use_cases",
    "anti_use_cases",
    "agent_keywords",
    "provides",
    "depends",
    "compatibility",
    "constraints",
    "example_refs",
    "integrations",
}

BOARD_KEYS = {
    "order",
    "name",
    "soc",
    "soc_family",
    "tier",
    "sdk_provider",
    "sdk_provider_module",
    "cpu",
    "toolchains",
    "registered",
}


def _builder():
    """Import scripts/docs/build_module_data.py without packaging scripts/."""

    if str(SCRIPTS) not in sys.path:
        sys.path.insert(0, str(SCRIPTS))
    return importlib.import_module("build_module_data")


@pytest.fixture(scope="module")
def builder():
    return _builder()


@pytest.fixture(scope="module")
def modules() -> dict[str, Any]:
    return json.loads(MODULES_SNAPSHOT.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def boards() -> dict[str, Any]:
    return json.loads(BOARDS_SNAPSHOT.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def registry_lock() -> dict[str, Any]:
    return yaml.safe_load(REGISTRY_LOCK.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# The snapshot describes this tree
# ---------------------------------------------------------------------------


def test_every_registry_module_is_in_the_snapshot(modules, registry_lock):
    assert {entry["name"] for entry in modules["modules"]} == set(registry_lock["modules"])
    assert modules["module_count"] == len(modules["modules"])


def test_the_snapshot_agrees_with_the_discovery_api(modules):
    """The registry fields come from the API, so they have to match it."""

    records = {record.name: record for record in list_modules(registry_only=True)}
    for entry in modules["modules"]:
        record = records[entry["name"]]
        assert entry["project"] == record.project
        assert entry["revision"] == record.revision
        assert entry["metadata_path"] == record.metadata


def test_every_module_carries_every_field(modules):
    for entry in modules["modules"]:
        assert set(entry) == MODULE_KEYS, entry["name"]
        assert entry["slug"] == entry["name"]
        assert isinstance(entry["capabilities"], list)
        assert isinstance(entry["use_cases"], list)
        assert isinstance(entry["anti_use_cases"], list)
        assert isinstance(entry["agent_keywords"], list)
        assert set(entry["depends"]) == {"required", "optional"}
        assert set(entry["compatibility"]) == {"boards", "socs", "toolchains"}


def test_every_module_declares_a_known_type(modules):
    for entry in modules["modules"]:
        if entry["manifest_source"] == "unavailable":
            continue
        assert entry["type"] in MODULE_TYPES, entry["name"]
        assert entry["version"], entry["name"]
        assert entry["compatibility"]["boards"], entry["name"]
        assert entry["compatibility"]["socs"], entry["name"]
        assert entry["compatibility"]["toolchains"], entry["name"]


def test_every_repo_url_is_the_registry_project_url(modules, registry_lock):
    for entry in modules["modules"]:
        project = registry_lock["projects"][entry["project"]]
        assert entry["repo_url"] == project["url"].removesuffix(".git")
        assert entry["source_url"] == f"{entry['repo_url']}/tree/{entry['revision']}"


def test_dependencies_name_modules_that_exist(modules):
    """Every dependency should be a module the catalog can link to.

    Four are not, so the catalog renders them as plain names rather than links.
    They are pinned here rather than ignored: the set is a fact about the
    registry, and a fifth one appearing should be somebody's decision, not a
    silent change to what the catalog links.
    """

    dangling_by_design = {
        ("nsx-ethos-u-driver", "nsx-harness"),
        ("nsx-power", "nsx-timer"),
        ("nsx-uart", "nsx-interrupt"),
        ("nsx-usb", "nsx-timer"),
    }
    known = {entry["name"] for entry in modules["modules"]}
    dangling = {
        (entry["name"], name)
        for entry in modules["modules"]
        for name in entry["depends"]["required"] + entry["depends"]["optional"]
        if name not in known
    }
    assert dangling == dangling_by_design


def test_the_snapshot_records_where_each_manifest_came_from(modules):
    sources = {entry["manifest_source"] for entry in modules["modules"]}
    assert sources <= {"packaged", "git", "unavailable"}
    for entry in modules["modules"]:
        if entry["manifest_source"] == "unavailable":
            assert entry["manifest_error"], entry["name"]
        else:
            assert entry["manifest_error"] is None, entry["name"]


def test_the_board_matrix_matches_every_board_descriptor(boards):
    descriptors = load_board_descriptors()
    assert [board["name"] for board in boards["boards"]] == list(BOARDS)
    assert boards["board_count"] == len(BOARDS)
    for index, board in enumerate(boards["boards"]):
        descriptor = descriptors[board["name"]]
        assert set(board) == BOARD_KEYS, board["name"]
        assert board["order"] == index
        assert board["soc"] == descriptor.soc
        assert board["tier"] == descriptor.tier
        assert board["sdk_provider"] == descriptor.sdk_provider
        assert board["registered"] == descriptor.registered
        assert board["toolchains"] == list(descriptor.toolchains)
        assert board["cpu"] == {
            "core": descriptor.cpu.core,
            "float_abi": descriptor.cpu.float_abi,
            "abi": descriptor.cpu.abi,
        }


def test_the_soc_families_match_the_registry_lock(boards, registry_lock):
    assert set(boards["soc_families"]) == set(registry_lock["soc_families"])
    for soc, family in boards["soc_families"].items():
        declared = registry_lock["soc_families"][soc]
        assert family["provider"] == declared.get("provider")
        assert family["project"] == declared.get("project")
        assert family["revision"] == declared.get("revision")
        assert family["modules"] == list(declared.get("modules") or [])


def test_every_board_soc_has_a_family(boards):
    for board in boards["boards"]:
        assert board["soc_family"] == board["soc"], board["name"]


def test_the_snapshot_makes_no_hardware_claim(modules):
    """Compatibility is declared by a manifest, so no manifest may say more."""

    forbidden = ("validated on", "tested on", "verified on", "hardware validated")
    for entry in modules["modules"]:
        prose = " ".join([
            entry["summary"] or "",
            *entry["use_cases"],
            *entry["anti_use_cases"],
        ]).lower()
        for phrase in forbidden:
            assert phrase not in prose, f"{entry['name']} claims {phrase!r}"


# ---------------------------------------------------------------------------
# The drift check catches drift
# ---------------------------------------------------------------------------


def _drift(builder, mutate) -> list[str]:
    """Run the comparison --check runs, against a snapshot mutated one way."""

    committed = json.loads(MODULES_SNAPSHOT.read_text(encoding="utf-8"))
    regenerated = copy.deepcopy(committed)
    mutate(regenerated)
    return builder.diff_summary(
        "modules.json", builder.serialize(regenerated), builder.serialize(committed)
    )


def test_an_unchanged_snapshot_reports_no_drift(builder):
    assert _drift(builder, lambda snapshot: None) == []


def test_a_changed_version_fails_the_check(builder):
    def mutate(snapshot):
        snapshot["modules"][0]["version"] = "99.0.0"

    lines = _drift(builder, mutate)
    assert lines, "a changed version did not register as drift"
    assert any("99.0.0" in line for line in lines)


def test_a_removed_module_fails_the_check(builder):
    def mutate(snapshot):
        removed = snapshot["modules"].pop()
        snapshot["module_count"] = len(snapshot["modules"])
        snapshot["removed"] = removed["name"]

    lines = _drift(builder, mutate)
    assert lines, "a removed module did not register as drift"


def test_an_added_field_fails_the_check(builder):
    def mutate(snapshot):
        snapshot["modules"][0]["boards_tested"] = ["apollo510_evb"]

    lines = _drift(builder, mutate)
    assert lines, "an added field did not register as drift"
    assert any("boards_tested" in line for line in lines)


def test_a_changed_board_fails_the_check(builder):
    committed = json.loads(BOARDS_SNAPSHOT.read_text(encoding="utf-8"))
    mutated = copy.deepcopy(committed)
    mutated["boards"][0]["tier"] = "production"
    lines = builder.diff_summary(
        "boards.json", builder.serialize(mutated), builder.serialize(committed)
    )
    assert lines, "a changed board tier did not register as drift"
    assert any("production" in line for line in lines)


def test_the_check_reports_a_missing_snapshot(builder, tmp_path, capsys):
    exit_code = builder.check(
        tmp_path / "modules.json",
        tmp_path / "boards.json",
        workspace=tmp_path / "workspace",
        offline=True,
    )
    assert exit_code == 1
    assert "does not exist" in capsys.readouterr().err


def test_an_unreadable_manifest_is_reported_rather_than_compared(builder, modules):
    """A private project answers a credential-less run with an access error.

    That is not drift, so the check carries the committed manifest fields over
    and names the module instead of failing on it.
    """

    regenerated = copy.deepcopy(modules)
    target = next(entry for entry in regenerated["modules"] if entry["manifest_source"] == "git")
    target["manifest_source"] = "unavailable"
    target["manifest_error"] = "repository not found"
    for field in builder.MANIFEST_FIELDS:
        target[field] = None

    reconciled, skipped = builder.reconcile_unavailable(regenerated, modules)
    assert skipped == [target["name"]]
    assert builder.serialize(reconciled) == builder.serialize(modules)


def test_a_module_missing_from_a_reachable_project_is_still_drift(builder, modules):
    """Reconciling an unreadable manifest must not paper over a real change."""

    regenerated = copy.deepcopy(modules)
    regenerated["modules"][0]["version"] = "99.0.0"
    reconciled, skipped = builder.reconcile_unavailable(regenerated, modules)
    assert skipped == []
    assert builder.diff_summary(
        "modules.json", builder.serialize(reconciled), builder.serialize(modules)
    )


def test_manifest_paths_resolve_the_way_the_resolver_resolves_them(builder, registry_lock):
    """The generator strips a project's own path prefix, as the resolver does."""

    assert builder.manifest_relpath("modules/helia-rt/nsx-module.yaml", "modules/helia-rt") == Path(
        "nsx-module.yaml"
    )
    assert builder.manifest_relpath(
        "modules/nsx-ambiqsuite/nsx-module.yaml", "modules/nsx-ambiq-sdk"
    ) == Path("modules/nsx-ambiqsuite/nsx-module.yaml")
    assert builder.manifest_relpath("modules/x/nsx-module.yaml", None) == Path(
        "modules/x/nsx-module.yaml"
    )


def test_the_offline_build_reads_the_manifests_this_repository_ships(builder, tmp_path, modules):
    """Without the network the packaged manifests still resolve, and only those."""

    offline = builder.build_modules(workspace=tmp_path, offline=True)
    committed = {entry["name"]: entry for entry in modules["modules"]}
    packaged = [entry for entry in offline["modules"] if entry["manifest_source"] == "packaged"]
    assert packaged, "no module resolves from packaged content"
    for entry in packaged:
        assert entry == committed[entry["name"]], entry["name"]
