# Auto-generated by neuralspotx. Included by app CMakeLists.
set(NSX_APP_MODULES
    nsx-cmsis-core
    nsx-ambiqsuite-r5
    nsx-ambiq-hal-r5
    nsx-ambiq-bsp-r5
    nsx-soc-hal
    nsx-cmsis-startup
    nsx-core
    nsx-interrupt
    nsx-gpio
    nsx-timer
    nsx-power
)

set(NSX_MODULE_DIR_nsx_cmsis_core "modules/nsx-ambiq-sdk-r5/modules/nsx-cmsis-core")
set(NSX_MODULE_DIR_nsx_ambiqsuite_r5 "modules/nsx-ambiq-sdk-r5/modules/nsx-ambiqsuite-r5")
set(NSX_MODULE_DIR_nsx_ambiq_hal_r5 "modules/nsx-ambiq-sdk-r5/modules/nsx-ambiq-hal-r5")
set(NSX_MODULE_DIR_nsx_ambiq_bsp_r5 "modules/nsx-ambiq-sdk-r5/modules/nsx-ambiq-bsp-r5")
set(NSX_MODULE_DIR_nsx_soc_hal "modules/nsx-ambiq-sdk-r5/modules/nsx-soc-hal")
set(NSX_MODULE_DIR_nsx_cmsis_startup "modules/nsx-ambiq-sdk-r5/modules/nsx-cmsis-startup")
set(NSX_MODULE_DIR_nsx_board_apollo510_evb "boards/apollo510_evb")
set(NSX_MODULE_DIR_nsx_core "modules/nsx-ambiq-sdk-r5/modules/nsx-core")
set(NSX_MODULE_DIR_nsx_interrupt "modules/nsx-ambiq-sdk-r5/modules/nsx-interrupt")
set(NSX_MODULE_DIR_nsx_gpio "modules/nsx-ambiq-sdk-r5/modules/nsx-gpio")
set(NSX_MODULE_DIR_nsx_timer "modules/nsx-ambiq-sdk-r5/modules/nsx-timer")
set(NSX_MODULE_DIR_nsx_power "modules/nsx-ambiq-sdk-r5/modules/nsx-power")
set(NSX_MODULE_DIR_nsx_tooling "cmake/nsx")

set(NSX_APP_PROJECT_DIRS
    modules/nsx-ambiq-sdk-r5
)
