# Auto-generated by neuralspotx. Included by app CMakeLists.
set(NSX_APP_MODULES
    nsx-ambiqsuite-r5
    nsx-ambiq-hal-r5
    nsx-ambiq-bsp-r5
    nsx-soc-hal
    nsx-cmsis-startup
    nsx-board-apollo510-evb
    nsx-core
    nsx-harness
    nsx-utils
    nsx-power
    nsx-tooling
)
