# Auto-generated from src/neuralspotx/constants.py BOARD_SDK_PROVIDER
# by scripts/gen_board_table.py — DO NOT EDIT.
#
# Defines: nsx_lookup_sdk_provider(board_name out_var)
#   Sets <out_var> in the parent scope to the canonical SDK
#   provider name (ambiqsuite-r3|ambiqsuite-r4|ambiqsuite-r5)
#   for the given board, or to the empty string if unknown.
#   Board matching is case-insensitive.

function(nsx_lookup_sdk_provider board_name out_var)
    string(TOLOWER "${board_name}" _board_lc)
    if(_board_lc STREQUAL "apollo2_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo3_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo3_evb_cygnus")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo3p_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo3p_evb_cygnus")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo4l_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo4l_blue_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo4p_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo4p_blue_kbr_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo4p_blue_kxr_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo5b_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo510_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo510b_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    elseif(_board_lc STREQUAL "apollo330mp_evb")
        set(${out_var} "ambiqsuite" PARENT_SCOPE)
    else()
        set(${out_var} "" PARENT_SCOPE)
    endif()
endfunction()
