/******************************************************************************
 * @file        resnet_tensors.h
 * @brief       Autogenerated tensor definitions
 * @details     Contains tensor definitions, arenas, and model I/O.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stddef.h>

// ABI guard fingerprint for the generated arena layout.
//
// SHA-256(role|memory|source_memory|size|alignment|is_staged) over
// every region in region_id order, truncated to 16 hex chars. Stays
// stable across re-plans of the same model and changes whenever any
// region's role / memory residency / size / alignment / staged
// status changes. Downstream binaries that hard-code arena region
// IDs can validate this matches the planner that built their loader
// before binding arenas.
#define RESNET_PLAN_HASH "19d806b6ac17194f"

//── Tensor/Memory Definitions ─────────────────────────────────────────────────

// Tensor ID enumeration
typedef enum {
    resnet_tensor_0 = 0,
    resnet_tensor_3 = 1,
    resnet_tensor_5 = 2,
    resnet_tensor_7 = 3,
    resnet_tensor_9 = 4,
    resnet_tensor_11 = 5,
    resnet_tensor_13 = 6,
    resnet_tensor_15 = 7,
    resnet_tensor_17 = 8,
    resnet_tensor_19 = 9,
    resnet_tensor_21 = 10,
    resnet_tensor_22 = 11,
    resnet_tensor_23 = 12,
    resnet_tensor_24 = 13,
    resnet_tensor_25 = 14,
    resnet_tensor_26 = 15,
    resnet_tensor_27 = 16,
    resnet_tensor_28 = 17,
    resnet_tensor_29 = 18,
    resnet_tensor_30 = 19,
    resnet_tensor_31 = 20,
    resnet_tensor_32 = 21,
    resnet_tensor_33 = 22,
    resnet_tensor_34 = 23,
    resnet_tensor_35 = 24,
    resnet_tensor_36 = 25,
    resnet_tensor_37 = 26,
    resnet_tensor_conv_2d_0_scratch = 27,
    resnet_tensor_conv_2d_0_weight_sum = 28,
    resnet_tensor_conv_2d_1_scratch = 29,
    resnet_tensor_conv_2d_1_weight_sum = 30,
    resnet_tensor_conv_2d_2_scratch = 31,
    resnet_tensor_conv_2d_2_weight_sum = 32,
    resnet_tensor_conv_2d_4_scratch = 33,
    resnet_tensor_conv_2d_4_weight_sum = 34,
    resnet_tensor_conv_2d_5_scratch = 35,
    resnet_tensor_conv_2d_5_weight_sum = 36,
    resnet_tensor_conv_2d_6_weight_sum = 37,
    resnet_tensor_conv_2d_8_scratch = 38,
    resnet_tensor_conv_2d_8_weight_sum = 39,
    resnet_tensor_conv_2d_9_scratch = 40,
    resnet_tensor_conv_2d_9_weight_sum = 41,
    resnet_tensor_conv_2d_10_weight_sum = 42,
    resnet_tensor_fully_connected_14_weight_sum = 43,
    resnet_num_tensors = 44
} resnet_tensor_ident_t;

// Input/Output descriptors
typedef struct {
    resnet_tensor_ident_t id;
    int8_t *data;  // pointer into context tensor_ptrs[]
    size_t size;  // Tensor size in bytes
    int32_t zero_point;  // Quantization zero-point
    float scale;  // Quantization scale
} resnet_tensor_io_t;

// Memory arenas enumeration. Region IDs come from the render plan's
// deterministic ordering policy (scratch < persistent < constant;
// within-role: memory.name ascending) so two re-plans of the same
// model produce identical enum values. The PLAN_HASH macro above
// fingerprints the same ordering for ABI drift detection.
typedef enum {
    resnet_arena_dtcm = 0,
    resnet_arena_const_dtcm = 1,
    resnet_num_arena_buffers = 2
} resnet_arena_region_t;

// Runtime status codes returned by the generated C API.
//
// Numeric values are organized into namespaced ranges so callers can
// disambiguate which API surface produced an error without
// out-of-band context:
//
//   * 0          : success.
//   * 1..4       : per-region ``resnet_bind_arena`` failures
//                  (also forwarded by ``resnet_bind_arenas`` for
//                  per-region issues).
//   * 10..12     : ``resnet_context_init`` /
//                  ``resnet_hydrate_constants`` preconditions.
//   * 13         : common ``ctx == NULL`` precondition failure
//                  shared across every public entry point.
//   * 14         : lifecycle precondition (``model_run`` before
//                  successful ``model_init``).
//   * 100..109   : ``resnet_bind_arenas`` bulk-argument failures.
//   * 200..209   : ``resnet_model_run`` precondition failures
//                  (e.g. hydration latch).
//
// Code that needs to inspect status values should prefer the
// enumerator names below; raw literals are reserved for snapshot /
// ABI-stability tests.
typedef enum {
    resnet_status_ok = 0,

    // bind_arena() per-region failures.
    resnet_status_bind_unknown_region   = 1,
    resnet_status_bind_null_buffer      = 2,
    resnet_status_bind_undersized       = 3,
    resnet_status_bind_misaligned       = 4,

    // context_init() / hydrate_constants() failures.
    resnet_status_context_arena_unbound = 10,
    // hydrate_constants() called on a context whose arena_buffers
    // table is still NULL (i.e. before context_init succeeded).
    resnet_status_hydrate_uninited_context = 11,
    resnet_status_hydrate_null_blob     = 12,

    // Common precondition failure (any public entry point).
    resnet_status_null_context          = 13,
    // model_run() called before model_init() succeeded.
    resnet_status_not_initialized       = 14,

    // bind_arenas() bulk-argument failures (per-region failures
    // forward the 1..4 range above).
    resnet_status_bind_bulk_null_argument = 100,
    resnet_status_bind_bulk_wrong_count   = 101,

    // model_run() precondition failures.
    resnet_status_hydration_required = 200,
} resnet_status_t;

// Tensor categories
typedef enum {
    resnet_tensor_type_constant,
    resnet_tensor_type_persistent,
    resnet_tensor_type_scratch,
} resnet_tensor_type_t;

// Tensor descriptors. Every tensor — scratch, persistent, or
// constant — is bound to an arena slot. The kernel-visible address
// is always ``arena_buffers[region] + offset``. There are no
// per-tensor C symbols.
typedef struct {
    resnet_tensor_type_t type;
    resnet_arena_region_t region;
    size_t offset;
    size_t size;
} resnet_tensor_descriptor_t;

//── Memory Arenas ─────────────────────────────────────────────────────────────

#define resnet_arena_dtcm_size  89088
#define resnet_arena_dtcm_alignment  16
#define resnet_arena_const_dtcm_size  237912
#define resnet_arena_const_dtcm_alignment  16

extern const void * const resnet_arena_buffers[resnet_num_arena_buffers];
/**
 * @brief Per-region capacity of every arena, in bytes.
 *
 * This table has **two** meanings, depending on the arena role:
 *
 *  - **Scratch / persistent / staged-constant** arenas:
 *    ``arena_sizes[region]`` is the runtime buffer size the caller
 *    must provide. In internal-arena mode the generated
 *    ``resnet_arena_*_buffer`` storage is exactly this size.
 *    In external-arena mode (``allocate_arenas=false``) the caller
 *    must bind a buffer at least this large via
 *    ``resnet_bind_arena``.
 *
 *  - **Cold-constant** arenas (``source_memory == memory``):
 *    ``arena_sizes[region]`` is the size of the cold blob in flash
 *    (or equivalent read-only memory). Kernels read the blob in
 *    place; there is no separate runtime buffer. In external-arena
 *    mode the caller must bind this region to a pointer to the
 *    cold blob itself (or to the matching ``__blob.bin`` sidecar
 *    when the C source omits the literal).
 *
 * Use ``resnet_tensor_descriptors[i].region`` to find which
 * arena a given tensor lives in, and the corresponding
 * ``arena_sizes[region]`` for its containing arena's capacity.
 */
extern const size_t resnet_arena_sizes[resnet_num_arena_buffers];

/**
 * @brief Per-region alignment requirement (bytes) for caller-supplied
 *        arena buffers in external-arena mode.
 *
 * Each value is a power of two and reflects the strictest alignment
 * required by any tensor placed in that arena (platform floor or
 * per-arena ``arena_alignment`` override, whichever is larger).
 * ``resnet_bind_arena`` returns status 4 if a buffer pointer
 * does not satisfy the corresponding entry. Internal-arena builds
 * (`allocate_arenas=true`) emit each buffer with
 * ``alignas(...)`` matching this table, so the constraint is
 * automatically met.
 */
extern const size_t resnet_arena_alignments[resnet_num_arena_buffers];

//── Model Input/Output ────────────────────────────────────────────────────────

#define resnet_num_inputs 1
#define resnet_num_outputs 1

#define resnet_input_0_size (3072)
#define resnet_output_0_size (10)

extern const resnet_tensor_ident_t resnet_inputs_id[resnet_num_inputs];
extern const resnet_tensor_ident_t resnet_outputs_id[resnet_num_outputs];
extern const int32_t resnet_inputs_len[resnet_num_inputs];
extern const int32_t resnet_inputs_zero_point[resnet_num_inputs];
extern const float resnet_inputs_scale[resnet_num_inputs];
extern const int32_t resnet_outputs_len[resnet_num_outputs];
extern const int32_t resnet_outputs_zero_point[resnet_num_outputs];
extern const float resnet_outputs_scale[resnet_num_outputs];

//── Model Tensors ─────────────────────────────────────────────────────────────

// Per-tensor byte size lives on the descriptor (``resnet_tensor_descriptors[i].size``);
// per-tensor element count is the descriptor size divided by the
// element width. Public ``_size`` macros are emitted only for model
// inputs/outputs above, where they are part of the stable I/O API.

// Tensor descriptors
extern const resnet_tensor_descriptor_t resnet_tensor_descriptors[resnet_num_tensors];

#ifdef __cplusplus
}
#endif