/******************************************************************************
 * @file        resnet_model.h
 * @brief       Autogenerated heliaAOT model
 * @details     Model: model - MLIR Converted.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "resnet_tensors.h"
#include "resnet_context.h"


/**
 * @brief heliaAOT model init
 *
 * Single entry point that wires up the context, hydrates any
 * staged-constant arenas (via the weak
 * ``resnet_hydrate_constants``), and runs every operator's
 * per-call init hook. Callers using ``model_init`` as the entry
 * point must NOT also call ``context_init`` separately: a second
 * ``context_init`` would clear both the lifecycle latch and the
 * hydration latch and a subsequent ``model_run`` would reject the
 * call.
 *
 * @param[in] ctx  The context struct
 *
 * @return ``resnet_status_ok`` (0) on success.
 *         ``resnet_status_null_context`` (13) if @p ctx is
 *         NULL.
 *         Any non-zero code forwarded from
 *         ``resnet_context_init`` (e.g. 10 for an unbound
 *         arena), from ``resnet_hydrate_constants`` for
 *         staged-constant builds, or from an operator's _init
 *         hook.
 *
 * @note Not thread-safe. See ``resnet_context_init``.
 */
int32_t resnet_model_init(
    resnet_model_context_t *ctx
);

/**
 * @brief heliaAOT model run
 *
 * @param[in] ctx  The context struct
 *
 * @return ``resnet_status_ok`` (0) on success; non-zero on
 *         failure.
 *         ``resnet_status_null_context`` (13) if @p ctx is
 *         NULL.
 *         ``resnet_status_not_initialized`` (14) if
 *         ``resnet_model_init`` was never called or failed.
 *
 * @note Not thread-safe. See ``resnet_context_init``.
 */
int32_t resnet_model_run(
    resnet_model_context_t *ctx
);

#ifdef __cplusplus
}
#endif