/******************************************************************************
 * @file        resnet_common.h
 * @brief       HeliaT common API
 * @details     Helper to pull in all common headers
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

//── 1) Compiler attributes and helpers ────────────────────────────────────────

#include "resnet_compiler.h"

//── 2) Standard C types and macros ────────────────────────────────────────────

#include <math.h>     // for isnan, isinf
#include <stddef.h>   // for size_t, NULL
#include <stdint.h>   // for int8_t, int32_t, etc.
#include <stdalign.h> // for alignas()
#include <stdbool.h>  // for bool, true, false

//── 3) Platform hooks ─────────────────────────────────────────────────────────

#include "resnet_platform.h"

//── 4) ns-cmsis-nn public API ─────────────────────────────────────────────────

#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"

// Verify ns-cmsis-nn version compatibility
#if (NS_CMSIS_NN_VERSION_MAJOR < 7) || \
    (NS_CMSIS_NN_VERSION_MAJOR == 7 && \
     NS_CMSIS_NN_VERSION_MINOR < 25)
  #error "CMSIS-NN version too old; need at least v7.25.0"
#endif

//── 5) AOT core definitions ───────────────────────────────────────────────────

#include "resnet_tensors.h"
#include "resnet_context.h"

#ifdef __cplusplus
}
#endif