/******************************************************************************
 * @file        resnet_operators.h
 * @brief       heliaAOT operators API
 * @details     Helper to pull in all operator headers
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "resnet_conv_2d_0.h"
#include "resnet_conv_2d_1.h"
#include "resnet_conv_2d_2.h"
#include "resnet_add_3.h"
#include "resnet_conv_2d_4.h"
#include "resnet_conv_2d_5.h"
#include "resnet_conv_2d_6.h"
#include "resnet_add_7.h"
#include "resnet_conv_2d_8.h"
#include "resnet_conv_2d_9.h"
#include "resnet_conv_2d_10.h"
#include "resnet_add_11.h"
#include "resnet_average_pool_2d_12.h"
#include "resnet_reshape_13.h"
#include "resnet_fully_connected_14.h"
#include "resnet_softmax_15.h"


#ifdef __cplusplus
}
#endif