/******************************************************************************
 * @file        resnet_context.h
 * @brief       heliaAOT model context API
 * @details     Defines and initializes the model context:
 *              - Assigns arena buffers & sizes
 *              - Registers callback & user_data
 *              - Populates tensor pointer arrays
 *              - Performs context-level validation
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "resnet_common.h"

//── Operator callback API ─────────────────────────────────────────────────────

// Operator states passed to the callback
typedef enum {
    resnet_op_state_init_started = 0,
    resnet_op_state_init_finished,
    resnet_op_state_run_started,
    resnet_op_state_run_finished,
} resnet_operator_state_t;

// Signature for the operator callback
typedef void (*resnet_operator_callback)(
    int32_t op, // Operator identifier
    resnet_operator_state_t state, // Operator state
    int32_t status, // Operator return code
    void *user_data // Opaque user data
);

//── Model‐execution context ───────────────────────────────────────────────────

// Holds all of the memory arenas, tensor pointers, model I/O, and user hooks
typedef struct {
    //── Public fields──────────────────────────────────────────────────────────

    // Operator callback handle
    resnet_operator_callback callback;
    void * user_data;

    //── Internal fields────────────────────────────────────────────────────────
    // Memory arenas for scratch tensors
    const void * const * arena_buffers;
    const size_t * arena_sizes;

    // Lifecycle latch: set to 1 only on successful model_init tail.
    // model_run early-returns status_not_initialized when this is 0.
    uint32_t _lifecycle_state;

    // Pointer table for *every* tensor (constant, persistent, scratch)
    int8_t *tensor_ptrs[resnet_num_tensors];

    // Convenience view for model I/O
    resnet_tensor_io_t inputs[resnet_num_inputs];
    resnet_tensor_io_t outputs[resnet_num_outputs];

} resnet_model_context_t;

/**
 * @brief heliaAOT context init
 *
 * Wires the per-tensor pointer table, populates the I/O convenience
 * views, clears the lifecycle latch (so a subsequent
 * ``resnet_model_run`` requires a successful
 * ``resnet_model_init``), and (for staged-constant builds)
 * clears the hydration latch.
 *
 * @note ``resnet_model_init`` calls this internally; callers
 *       using ``resnet_model_init`` as the entry point must
 *       NOT also call ``resnet_context_init`` separately.
 *       Doing so would clear both the lifecycle and hydration
 *       latches, requiring a full ``resnet_model_init`` (and,
 *       for manual-hydration builds,
 *       ``resnet_hydrate_constants``) before
 *       ``resnet_model_run`` will succeed again.
 *
 * @note Not thread-safe. The arena binding table and hydration latch
 *       are module-global; concurrent calls from multiple threads
 *       must be serialized externally.
 *
 * @param[in] ctx  The context struct to populate
 * @return ``resnet_status_ok`` (0) on success.
 *         ``resnet_status_null_context`` (13) if @p ctx is
 *         NULL.
 *         ``resnet_status_context_arena_unbound`` (10) if any
 *         arena region has not been bound (external-arena mode
 *         only; see ``resnet_bind_arena``).
 */
int32_t resnet_context_init(
    resnet_model_context_t *ctx
);

#ifdef __cplusplus
}
#endif