/******************************************************************************
 * @file        resnet_compiler.h
 * @brief       heliaAOT compiler API
 * @details     Define compiler-specific attributes and helpers.
 * @date        2026-06-09
 * @version     0.17.1
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

//── Compiler attributes ───────────────────────────────────────────────────


#ifdef __cplusplus
}
#endif